name: ci-test
description: Test golang code

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  # aws inputs
  aws-role-duration-seconds:
    description: ""
    required: false
    default: "900"
  aws-region:
    description: ""
    required: false
  # gati inputs
  use-gati:
    description: ""
    required: false
    default: "false"
  aws-role-arn-gati:
    description: ""
    required: false
  aws-lambda-url-gati:
    description: ""
    required: false
  # env inputs
  use-env-files:
    description: ""
    required: false
    default: "false"
  env-files:
    description: "<env-file-1>|<env-file-2>|..."
    required: false
    default: .env
  # golang inputs
  use-go-cache:
    description: ""
    required: false
    default: "false"
  go-cache-dep-path:
    description: ""
    required: false
    default: go.sum
  go-version-file:
    description: ""
    required: false
    default: go.mod
  go-test-cmd:
    description: ""
    required: false
    default: go test ./...
  go-test-race-cmd:
    description: |
      Command to run Go tests with race detection enabled. This command is used to
      execute the Go test suite while checking for race conditions. By default,
      it runs `go test` with the `-race` flag to enable the race detector, along
      with flags for code coverage. The default command is:

      `go test -race ./... -coverpkg=./... -coverprofile=race_coverage.txt`

      - `-race` enables the race detector to identify concurrent access issues.
      - `./...` specifies that all tests in the module should be run.
      - `-coverpkg=./...` includes coverage for all packages.
      - `-coverprofile=race_coverage.txt` generates a coverage report file named `race_coverage.txt`.

      Customize this command if you need different flags or configurations for your testing environment.
    required: false
    default: go test -race ./... -coverpkg=./... -coverprofile=race_coverage.txt

  enable-go-test-race:
    description: |
      Specifies whether to enable the Go race detector when running tests.
      When set to "true", the race detector will be activated, which helps
      identify race conditions in concurrent Go code. By default, this is set
      to "false", meaning race detection is disabled unless explicitly enabled.
    required: false
    default: "false"
  # docker-compose inputs
  use-docker-compose:
    description: ""
    required: false
    default: "false"
  docker-compose-workdir:
    description: ""
    required: false
    default: "."
  # grafana inputs (optional)
  metrics-job-name:
    description: "grafana metrics job name"
    required: false
  metrics-id:
    description:
      "grafana metrics id, used for continuity of metrics during job name
      changes - required if metrics-job-name is passed"
    required: false
  gc-host:
    description: "grafana hostname - required if metrics-job-name is passed"
    required: false
  gc-basic-auth:
    description: "grafana basic auth - required if metrics-job-name is passed"
    required: false
  gc-org-id:
    description:
      "grafana org/tenant id - required if metrics-job-name is passed"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Assume aws gati role
      if: inputs.use-gati == 'true'
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: ${{ inputs.aws-role-arn-gati }}
        role-duration-seconds: ${{ inputs.aws-role-duration-seconds }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true

    - name: Get github token from gati
      if: inputs.use-gati == 'true'
      id: get-gh-token
      uses: smartcontractkit/chainlink-github-actions/github-app-token-issuer@main
      with:
        url: ${{ inputs.aws-lambda-url-gati }}

    - name: Configure github token
      if: inputs.use-gati == 'true'
      shell: bash
      run: |
        git config --global \
          url."https://x-access-token:${{ steps.get-gh-token.outputs.access-token }}@github.com/".insteadOf \
          "https://github.com/"

    - name: Set env from files
      if: inputs.use-env-files == 'true'
      uses: cardinalby/export-env-action@b16a08b396d047e3f9e1446e3946440e2be02a73 # 2.2.2
      with:
        envFile: ${{ inputs.env-files }}

    - name: Run docker-compose
      if: inputs.use-docker-compose == 'true'
      shell: bash
      run: docker compose up -d
      working-directory: ${{ inputs.docker-compose-workdir }}

    - name: Setup go
      uses: smartcontractkit/.github/actions/setup-golang@c5e1a1a754f459440b084c6661538b8635dcb33a # setup-golang@0.2.0
      with:
        go-version-file: ${{ inputs.go-version-file }}
        use-go-cache: ${{ inputs.use-go-cache }}
        go-cache-dep-path: ${{ inputs.go-cache-dep-path }}

    - name: Run go test
      shell: bash
      run: |
        set -o pipefail
        ${{ inputs.go-test-cmd }}

    - name: Run go tests with race detector
      if: inputs.enable-go-test-race == 'true'
      shell: bash
      run: |
        set -o pipefail
        ${{ inputs.go-test-race-cmd }}

    - name: Store test report artifacts
      if: always()
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: go-test-results
        path: |
          ./coverage.txt
          ./output.txt

    - name: Store race coverage report
      if: ${{ inputs.enable-go-test-race == 'true' }}
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: go-test-race-results
        path: ./race_coverage.txt

    - name: Collect metrics
      if: always() && inputs.metrics-job-name != ''
      id: collect-gha-metrics
      uses: smartcontractkit/push-gha-metrics-action@d9da21a2747016b3e13de58c7d4115a3d5c97935 # v3.0.1
      with:
        id: ${{ inputs.metrics-id || inputs.metrics-job-name }}
        basic-auth: ${{ inputs.gc-basic-auth }}
        hostname: ${{ inputs.gc-host }}
        org-id: ${{ inputs.gc-org-id}}
        this-job-name: ${{ inputs.metrics-job-name }}
      continue-on-error: true
