name: changed-modules-go
description: "Gets the go modules changed for a github event"

inputs:
  ignore-files:
    description: |
      A comma-separated list of glob patterns to ignore when detecting changed files.
      Files which match any of these patterns will be removed from the list of changed files, which determines which modules are considered changed.
    required: false
    default: ""

  ignore-modules:
    description: |
      A comma-separated list of glob patterns to ignore when finding modules.
      Modules in this list will never be considered changed, even if files within them have changed.
      Note: a pattern like 'module/**' will ignore all modules within the module/ directory, and the module/ itself. Use 'module/**/*' to only ignore sub-modules.
    required: false
    default: ""

  schedule-behaviour:
    description: |
      Defines the behaviour of the action when triggered by a schedule event.
      Options are:
      - 'all': All modules will be considered changed (will still respect ignore-modules).
      - 'none': No modules will be considered changed.
    required: false
    default: "all"

outputs:
  modified-modules:
    description: |
      The paths to the go modules, relative to the CWD, separated by commas

runs:
  using: "node20"
  main: "dist/index.js"
