name: changed-modules-go
description: "Gets the go modules changed for a github event"

inputs:
  file-patterns:
    description: |
      A comma or newline-separated list of glob patterns to include when determining changed modules.
      Only files matching these patterns will be considered when determining which modules have changed.
      Supports standard glob syntax. Any negations (exclusions) are processed first (e.g. '!**/*_test.go' to exclude test files).
    required: false
    default: "**/*.go,**/go.mod,**/go.sum"

  module-patterns:
    description: |
      A comma or newline-separated list of glob patterns to match module paths to include when determining changed modules.
      Only modules matching these patterns will be considered when determining which modules have changed.
      Supports standard glob syntax. Any negations (exclusions) are processed first (e.g. '!**/test/**' to exclude test modules).
    required: false
    default: "**"

  no-change-behaviour:
    description: |
      Defines the behaviour of the action when triggered by events that do not have an associated changeset.
      Right now only supports: schedule, workflow_dispatch. All below options still respect ignore-files and ignore-modules.
      Options are:
      - 'all': All modules will be considered changed.
      - 'root': Only the root module (.) will be considered changed.
      - 'latest-commit': Only modules changed in the latest commit will be considered changed.
      - 'none': No modules will be considered changed.
    required: false
    default: "all"

outputs:
  modified-modules-csv:
    description: |
      The paths to the go modules, relative to the CWD, separated by commas
  modified-modules-json:
    description: |
      A JSON array of the paths to the go modules, relative to the CWD

runs:
  using: "node20"
  main: "dist/index.js"
