name: changed-modules-go
description: "gets the go modules changed for a github event"

inputs:
  sub-directory:
    description:
      "The sub-directory to search for go.mod files. Defaults to './'"
    required: false
    default: "./"

  # ref inputs
  base-ref:
    description: "Base branch or commit to compare against"
    required: false
    default: "${{ github.event.pull_request.base.ref }}"
  head-ref:
    description: "Head branch or commit to compare against"
    required: false
    default: "${{ github.event.pull_request.head.ref }}"

outputs:
  modified-modules:
    description: |
      The paths to the go modules, relative to the CWD, separated by commas

runs:
  using: "node20"
  main: "dist/index.js"
