name: Validate Go Mod Files

on:
  pull_request:

jobs:
  go-mod-validation:
    name: Validate go.mod dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Validate go.mod
        uses: smartcontractkit/.github/apps/go-mod-validator@3deb8db9f687eee0678d2411ef40074078173e9a #v0.2.1
