name: ci-sonarqube-go
description: Add SonarQube for Golang to CI for code coverage

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  # sonarqube inputs
  sonar-token:
    description: "sonarqube token"
    required: false
  sonar-host-url:
    description: "sonarqube host url"
    required: false
  test-report-workflow:
    description:
      "workflow file name from where test report artifact was uploaded"
    required: false
  test-report-artifact:
    description: "Name of artifact containing junit test and coverage results"
    required: false
    default: "go-test-results"
  test-result-report-path:
    description: "paths to Go test results in txt format"
    requried: false
    default: "output.txt"
  test-coverage-report-path:
    description: "paths to Go test coverage report in txt format"
    requried: false
    default: "coverage.txt"
  lint-report-workflow:
    description:
      "workflow file name from where lint report artifact was uploaded"
    required: false
  lint-report-artifact:
    description: "Name of artifact containing golangci-lint report"
    requried: false
    default: "golangci-lint-report"
  lint-report-path:
    description: "paths to golangci-lint report in xml format"
    requried: false
    default: "golangci-lint-report.xml"
  include-lint:
    description: "enable linting"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Download test-report artifact using workflow file name
      if: inputs.test-report-workflow != ''
      uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
      with:
        workflow: ${{ inputs.test-report-workflow }}
        name: ${{ inputs.test-report-artifact }}
        workflow_conclusion: "" # ignore workflow status to let the latest artifact be downloaded

    - name: Download test-report artifact from current workflow
      if: inputs.test-report-workflow == ''
      uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
      with:
        name: ${{ inputs.test-report-artifact }}
        workflow_conclusion: ""

    - name: Download lint-report artifact using workflow file name
      if: inputs.lint-report-workflow != ''
      uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
      with:
        workflow: ${{ inputs.lint-report-workflow }}
        name: ${{ inputs.lint-report-artifact }}
        workflow_conclusion: ""

    - name: Download lint-report artifact from current workflow
      if: inputs.lint-report-workflow == ''
      uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
      with:
        name: ${{ inputs.lint-report-artifact }}
        workflow_conclusion: ""

    - name: SonarQube scan without lint
      if: inputs.include-lint == 'false'
      uses: sonarsource/sonarqube-scan-action@aecaf43ae57e412bd97d70ef9ce6076e672fe0a9 # v2.3.0
      with:
        args: >
          -Dsonar.go.tests.reportPaths=${{
            inputs.test-result-report-path
          }} -Dsonar.go.coverage.reportPaths=${{
            inputs.test-coverage-report-path
          }}
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}

    - name: SonarQube scan with lint
      if: inputs.include-lint == 'true'
      uses: sonarsource/sonarqube-scan-action@aecaf43ae57e412bd97d70ef9ce6076e672fe0a9 # v2.3.0
      with:
        args: >
          -Dsonar.go.tests.reportPaths=${{
            inputs.test-result-report-path
          }} -Dsonar.go.coverage.reportPaths=${{
            inputs.test-coverage-report-path
          }} -Dsonar.go.golangci-lint.reportPaths=${{
            inputs.lint-report-path
          }}
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
