name: ci-sonarqube-go
description: Add SonarQube for Golang to CI for code coverage

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  # sonarqube inputs
  sonar-token:
    description: "sonarqube token"
    required: false
  sonar-host-url:
    description: "sonarqube host url"
    required: false
  test-report-workflow:
    description: "workflow file name which uploaded test report artifacts"
    required: false
  test-report-artifact:
    description: "Name of artifact containing junit test and coverage results"
    required: false
    default: go-test-results
  test-report-name:
    description: "Go coverage report name with extension"
    requried: false
    default: "coverage.txt"
  lint-report-workflow:
    description: "workflow file name which uploaded lint report artifacts"
    required: false
  lint-report-artifact:
    description: "Name of artifact containing golangci-lint report"
    requried: false
    default: golangci-lint-report
  lint-report-name:
    description: "Golangci-lint report name with extension"
    requried: false
    default: "golangci-lint-report.xml"
  include-lint:
    description: "enable linting"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Download all reports (no test-report-workflow)
      id: all
      if: inputs.test-report-workflow == ''
      uses: actions/download-artifact@v4

    - name: Download all reports (no lint-report-workflow)
      if: steps.all.outcome != 'success' && inputs.lint-report-workflow == ''
      uses: actions/download-artifact@v4

    - name: Download test-report artifact using workflow file name
      if: inputs.test-report-workflow != ''
      uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
      with:
        workflow: ${{ inputs.test-report-workflow }}
        name: ${{ inputs.test-report-artifact }}
        search_artifacts: true
        workflow_conclusion: "" # ignore workflow status to let the latest artifact be downloaded
        if_no_artifact_found: warn

    - name: Download lint-report artifact using workflow file name
      if: inputs.lint-report-workflow != ''
      uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
      with:
        workflow: ${{ inputs.lint-report-workflow }}
        name: ${{ inputs.lint-report-artifact }}
        search_artifacts: true
        workflow_conclusion: ""
        if_no_artifact_found: warn

    - name: Set SonarQube Report Paths
      shell: bash
      run: |
        sonarqube_coverage_report_paths=$(find -type f -name '${{ inputs.test-report-name }}' -printf "%p,")
        sonarqube_golangci_report_paths=$(find -type f -name '${{ inputs.lint-report-name }}' -printf "%p,")
        ARGS=""
        ARGS="$ARGS -Dsonar.go.coverage.reportPaths=$sonarqube_coverage_report_paths"
        ARGS="$ARGS -Dsonar.go.golangci-lint.reportPaths=$sonarqube_golangci_report_paths"
        echo "SONARQUBE_ARGS=$ARGS" >> $GITHUB_ENV

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@0c0f3958d90fc466625f1d1af1f47bddd4cc6bd1 # v3.0.0
      with:
        args: ${{ env.SONARQUBE_ARGS }}
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
