name: beholder-pulumi-deploy-schema
description:
  "Validates and deploys a Protobuf or AVRO schema to Confluent Schema Registry"

inputs:
  pulumi_s3_bucket:
    description: "S3 bucket name to use as Pulumi backend"
    required: true
  aws_account_id:
    description: "AWS Account ID"
    required: false
    default: "804282218731"
  aws_region:
    description: "AWS region"
    required: false
    default: "us-west-2"

env:
  PULUMI_S3_BUCKET: ${{ github.event.inputs.pulumi_s3_bucket }}
  AWS_ACCOUNT_ID: ${{ github.event.inputs.aws_account_id }}
  AWS_REGION: ${{ github.event.inputs.aws_region }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
  CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
  CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
  SCHEMA_REGISTRY_KEY: ${{ secrets.SCHEMA_REGISTRY_KEY }}
  SCHEMA_REGISTRY_SECRET: ${{ secrets.SCHEMA_REGISTRY_SECRET }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.2.1

    - name: Configure AWS Credentials
      shell: bash
      run: |
        aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
        aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
        aws configure set default.region "${AWS_REGION}"

    - name: Install Pulumi
      shell: bash
      run: |
        curl -fsSL https://get.pulumi.com | sh
        echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

    - name: Pulumi Login
      shell: bash
      run: pulumi login s3://${PULUMI_S3_BUCKET}

    - name: Docker login to ECR
      shell: bash
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

    - name: Pull container image
      shell: bash
      run: |
        docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/atlas-beholder-pulumi:519065ab69c91995d1695679807619d77c031522

    - name: Deploy schema
      shell: bash
      run: |
        docker run \
          -e CONFLUENT_CLOUD_API_KEY="${CONFLUENT_CLOUD_API_KEY}" \
          -e CONFLUENT_CLOUD_API_SECRET="${CONFLUENT_CLOUD_API_SECRET}" \
          -e SCHEMA_REGISTRY_KEY="${SCHEMA_REGISTRY_KEY}" \
          -e SCHEMA_REGISTRY_SECRET="${SCHEMA_REGISTRY_SECRET}" \
          -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
          -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
          -e PULUMI_CONFIG_PASSPHRASE="${PULUMI_CONFIG_PASSPHRASE}" \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/atlas-beholder-pulumi schemas-deployment
