name: ci-test
description: Test typescript code

inputs:
  # github token to pass to tests
  github-token:
    description: "github token"
    default: ${{ github.token }}
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  check-only-affected:
    description: ""
    required: false
    default: "false"
  # nodejs inputs
  node-version-file:
    description: ""
    required: false
    default: ".tool-versions"
  pnpm-version:
    description: ""
    required: false
    default: "^8.0.0"

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Setup nodejs
      uses: smartcontractkit/.github/actions/setup-nodejs@main
      with:
        node-version-file: ${{ inputs.node-version-file }}
        pnpm-version: ${{ inputs.pnpm-version }}
        use-cache: "true"
        run-install: "true"
      continue-on-error: true

    - name: Run test
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: pnpm run test

    - name: Run lint affected
      if: inputs.check-only-affected == 'true'
      shell: bash
      run: pnpm run test:affected

    - name: Store test result artifacts
      if: always()
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: ts-test-results
        path: |
          ./junit.xml
          ./lcov.info
