packages:
  - actions/**
  - "!actions/signed-commits/__fixtures__/**"
  - libs/**
  - apps/**
  - workflows/**
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - lefthook
  - nice-napi
  - nx
  - unrs-resolver
