name: ctf-build-test-image
description:
  Action that allows building and publishing the test remote runner image for
  Chainlink Testing Framework

inputs:
  repository:
    description: The docker repository for the image
    default: chainlink-tests
    required: false
  tag:
    description:
      The tag to use by default and to use for checking image existence. If not
      provided, the hash of the integration-tests/ directory will be used
    required: false
  other_tags:
    description: Other tags to push if needed
    required: false
  suites:
    description: The test suites to build into the image
    default: chaos migration reorg smoke soak benchmark load
    required: false
  QA_AWS_ROLE_TO_ASSUME:
    description:
      The AWS role to assume as the CD user, if any. Used in configuring the
      docker/login-action
    required: true
  QA_AWS_REGION:
    description:
      The AWS region the ECR repository is located in, should only be needed for
      public ECR repositories, used in configuring docker/login-action
    required: true
  QA_AWS_ACCOUNT_NUMBER:
    description:
      The AWS region the ECR repository is located in, should only be needed for
      public ECR repositories, used in configuring docker/login-action
    required: true

outputs:
  test_image:
    description: The full name of the test image that was built
    value: ${{ steps.image_outputs.outputs.test_image }}
  test_image_tag:
    description: The tag of the test image that was built
    value: ${{ steps.image_outputs.outputs.test_image_tag }}
  test_image_repository:
    description: The repository of the test image that was built
    value: ${{ steps.image_outputs.outputs.test_image_repo }}

runs:
  using: composite
  steps:
    # Base Test Image Logic
    - name: Get CTF Version
      id: version
      uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/mod-version@1ada5d85b0de3439a0ba238210d40605b5ed6704 # v2.3.32
      with:
        go-project-path: ./integration-tests
        module-name: github.com/smartcontractkit/chainlink-testing-framework/lib
        enforce-semantic-tag: false
    - name: Get CTF sha
      if: steps.version.outputs.is_semantic == 'false'
      id: short_sha
      env:
        VERSION: ${{ steps.version.outputs.version }}
      shell: bash
      run: |
        short_sha="${VERSION##*-}"
        echo "short sha is: ${short_sha}"
        echo "short_sha=${short_sha}" >> "$GITHUB_OUTPUT"
    - name: Checkout chainlink-testing-framework
      if: steps.version.outputs.is_semantic == 'false'
      uses: actions/checkout@v4
      with:
        repository: smartcontractkit/chainlink-testing-framework
        ref: main
        fetch-depth: 0
        path: ctf
    - name: Get long sha
      if: steps.version.outputs.is_semantic == 'false'
      id: long_sha
      env:
        SHORT_SHA: ${{ steps.short_sha.outputs.short_sha }}
      shell: bash
      run: |
        cd ctf
        long_sha=$(git rev-parse ${SHORT_SHA})
        echo "sha is: ${long_sha}"
        echo "long_sha=${long_sha}" >> "$GITHUB_OUTPUT"
    - name: Check if test base image exists
      if: steps.version.outputs.is_semantic == 'false'
      id: check-base-image
      uses: smartcontractkit/chainlink-github-actions/docker/image-exists@1ada5d85b0de3439a0ba238210d40605b5ed6704 # v2.3.32
      with:
        repository: test-base-image
        tag: ${{ steps.long_sha.outputs.long_sha }}
        AWS_REGION: ${{ inputs.QA_AWS_REGION }}
        AWS_ROLE_TO_ASSUME: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
    - name: Build Base Image
      id: build_base_image
      continue-on-error: true
      if:
        steps.version.outputs.is_semantic == 'false' &&
        steps.check-base-image.outputs.exists == 'false'
      uses: smartcontractkit/chainlink-github-actions/docker/build-push@1ada5d85b0de3439a0ba238210d40605b5ed6704 # v2.3.32
      env:
        BASE_IMAGE_NAME:
          ${{ inputs.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ inputs.QA_AWS_REGION
          }}.amazonaws.com/test-base-image:${{ steps.long_sha.outputs.long_sha
          }}
      with:
        tags: ${{ env.BASE_IMAGE_NAME }}
        file: ctf/lib/k8s/Dockerfile.base
        AWS_REGION: ${{ inputs.QA_AWS_REGION }}
        AWS_ROLE_TO_ASSUME: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
    - name: Report Base Image build failure
      if:
        steps.version.outputs.is_semantic == 'false' &&
        steps.check-base-image.outputs.exists == 'false' &&
        steps.build_base_image.outcome == 'failure'
      shell: bash
      env:
        BASE_IMAGE_NAME:
          ${{ inputs.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ inputs.QA_AWS_REGION
          }}.amazonaws.com/test-base-image:${{ steps.long_sha.outputs.long_sha
          }}
      run: |
        echo "::error::Failed to build base image ${BASE_IMAGE_NAME}. It's likely that the go versions are mismatched. Try updating the base image go version here: https://github.com/smartcontractkit/chainlink-testing-framework/blob/main/lib/k8s/Dockerfile.base#L2"
        {
          echo "## Base image build failed"
          echo ""
          echo "It's likely that the go versions are mismatched. Try updating the base image go version here: https://github.com/smartcontractkit/chainlink-testing-framework/blob/main/lib/k8s/Dockerfile.base#L2 and then run the Publish Test Base Image CI workflow."
        } >> "$GITHUB_STEP_SUMMARY"
        exit 1
    # End Base Image Logic
    # Test Runner Logic
    - name: Get hash of integration-tests/ for test runner image
      id: test_runner_hash
      if: ${{ inputs.tag == '' }}
      # Do not include testconfig/ in the hash to avoid rebuilding the image when only testconfig/ changes
      shell: sh
      run: |
        HASH_VALUE=$(echo -n "${{ inputs.suites }} $(find integration-tests -type f ! -path 'integration-tests/testconfig/overrides/*.toml' ! -path 'integration-tests/testconfig/overrides/*/*.toml' ! -path 'integration-tests/testconfig/*/overrides/*.toml' ! -path 'integration-tests/testconfig/*/overrides/*/*.toml' ! -path 'integration-tests/ccip-tests/testconfig/*/overrides/*.toml' ! -path 'integration-tests/ccip-tests/testconfig/*/overrides/*/*.toml' ! -path '.github/*/*' ! -path '*/*.md' ! -path '*/*.MD' ! -path 'integration-tests/*/__debug_bin*' ! -path '*/*.MD' ! -path 'integration-tests/*/tmp-manifest*.yaml' ! -path '*/*.MD' ! -path 'integration-tests/*/*.log' ! -path 'integration-tests/*/*_dump.sql' ! -path 'integration-tests/*/.test_summary/*' -exec sha256sum {} + | sort -k 2 | sha256sum | awk '{print $1}')" | sha256sum | awk '{print $1}')
        echo "Computed hash: $HASH_VALUE"
        echo "hash_value=$HASH_VALUE" >> $GITHUB_OUTPUT

    - name: Check if image exists
      id: check-image
      uses: smartcontractkit/chainlink-github-actions/docker/image-exists@1ada5d85b0de3439a0ba238210d40605b5ed6704 # v2.3.32
      with:
        repository: ${{ inputs.repository }}
        tag: ${{ inputs.tag || steps.test_runner_hash.outputs.hash_value }}
        AWS_REGION: ${{ inputs.QA_AWS_REGION }}
        AWS_ROLE_TO_ASSUME: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
    - name: Build and Publish Test Runner
      if: steps.check-image.outputs.exists == 'false'
      uses: smartcontractkit/chainlink-github-actions/docker/build-push@1ada5d85b0de3439a0ba238210d40605b5ed6704 # v2.3.32
      with:
        tags: |
          ${{ inputs.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ inputs.QA_AWS_REGION }}.amazonaws.com/${{ inputs.repository }}:${{ inputs.tag || steps.test_runner_hash.outputs.hash_value }}
          ${{ inputs.other_tags }}
        file: ./integration-tests/test.Dockerfile
        build-args: |
          BASE_IMAGE=${{ inputs.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ inputs.QA_AWS_REGION }}.amazonaws.com/test-base-image
          IMAGE_VERSION=${{ steps.long_sha.outputs.long_sha || steps.version.outputs.version }}
          SUITES="${{ inputs.suites }}"
        AWS_REGION: ${{ inputs.QA_AWS_REGION }}
        AWS_ROLE_TO_ASSUME: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
    - name: Print Image Built
      shell: sh
      env:
        INPUTS_REPOSITORY: ${{ inputs.repository }}
        INPUTS_TAG:
          ${{ inputs.tag || steps.test_runner_hash.outputs.hash_value }}
      run: |
        echo "### ${INPUTS_REPOSITORY} image tag for this test run :ship:" >> $GITHUB_STEP_SUMMARY
        echo "\`${INPUTS_TAG}\`" >> $GITHUB_STEP_SUMMARY
    - name: Set outputs
      id: image_outputs
      shell: sh
      run: |
        echo "test_image_repo=${{ inputs.repository }}" >> $GITHUB_OUTPUT
        echo "test_image_tag=${{ inputs.tag || steps.test_runner_hash.outputs.hash_value }}" >> $GITHUB_OUTPUT
        echo "test_image=${{ inputs.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ inputs.QA_AWS_REGION }}.amazonaws.com/${{ inputs.repository }}:${{ inputs.tag || steps.test_runner_hash.outputs.hash_value }}" >> $GITHUB_OUTPUT
    # End Test Runner Logic
