name: ci-prettier
description: Prettier Code Formatter

inputs:
  # specific inputs
  prettier-command:
    description: "Command to run prettier"
    required: false
    default: "pnpm run prettier:check"
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  # nodejs inputs
  node-version-file:
    description: ""
    required: false
    default: ".tool-versions"
  nodejs-version:
    description:
      "NodeJS version used only if the node-version-file isn't provided"
    required: false
    default: "^20.16.0"
  pnpm-version:
    description: ""
    required: false
    default: "^9.0.0"

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Create .tool-versions file if it doesn't exist
      shell: bash
      run: |
        if [ ! -f "${{ inputs.node-version-file }}" ]; then
          echo "nodejs ${{ inputs.nodejs-version }}" > ${{ inputs.node-version-file }}
        fi

    - name: Setup nodejs
      uses: smartcontractkit/.github/actions/setup-nodejs@8fb84214197a54beaf10afd4fdb258f74b41de1a # setup-nodejs@0.2.3
      with:
        node-version-file: ${{ inputs.node-version-file }}
        pnpm-version: ${{ inputs.pnpm-version }}
        use-cache: "true"
        run-install: "true"
      continue-on-error: true

    # Prettier must be available in the project's package.json as a dep.
    - name: Run Prettier Check
      shell: bash
      run: ${{ inputs.prettier-command }}
