name: go-mod-validator
description:
  "Validates that the git references contained in dependencies within go.mod
  files exist in their respective default branches"

inputs:
  github-token:
    description:
      "Github token with read permissions on all smartcontractkit repos"
    default: ${{ github.token }}
  github-pr-read-token:
    description:
      "Github API token with pull-requests: read, for the currrent repository.
      Defaults to the above github token if not provided."
    required: false
  go-mod-dir:
    description: "Common directory where go.mod files are located"
    default: ${{ github.workspace }}
  dep-prefix:
    description: "Prefix to filter dependencies by"
    default: "github.com/smartcontractkit"
  repo-branch-exceptions:
    description: |
      Each line should contain a repository and a comma separated list of branches.
      Format: <owner>/<repo>:<branch1>,<branch2>,...
      Can include the same repo multiple times to append more branches.
      Example:
        smartcontractkit/chainlink:main,release/2.30.1
        smartcontractkit/chainlink-ccip:develop
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"
