name: go-mod-validator
description: "Validates dependencies in go.mod files are tested"

inputs:
  github-token:
    description: "github token to fetch upstream dependencies"
    required: true
    default: ${{ github.token }}
  go-mod-file-dir:
    description: "dir where go.mod file is located"
    required: false
    default: ${{ github.workspace }}

runs:
  using: "node20"
  main: "dist/index.js"
