/**
 * Medic Conflict Generator - Creates test PRs with merge conflicts
 * 
 * This action generates a new PR that will have a merge conflict with main.
 * Used for testing the medic conflict resolution capability.
 * 
 * Triggers:
 * - Comment "/medic generate conflict" on any issue/PR
 * - Manual workflow dispatch with generate-conflict=true
 * 
 * Process:
 * 1. Validate commenter is authorized
 * 2. Find the commit that last modified CONFLICT.md on main
 * 3. Create branch from the PARENT of that commit (to ensure conflict)
 * 4. Modify CONFLICT.md with timestamp value
 * 5. Push branch and create PR
 * 6. Comment with link to new PR
 * 
 * Why branch from parent? For a merge conflict to occur, both main and the PR
 * branch must have divergent changes to the same file from a common ancestor.
 * By branching from before the last CONFLICT.md change, we ensure both branches
 * have modifications to CONFLICT.md relative to the merge base.
 */

import * as core from '@actions/core';
import * as exec from '@actions/exec';
import * as github from '@actions/github';
import { isAuthorAllowed } from './config.js';
import type { OctokitClient } from './types.js';

const CONFLICT_FILE = 'CONFLICT.md';

/**
 * Inputs for the conflict generator action
 */
interface GeneratorInputs {
  githubToken: string;
  triggerType: 'comment' | 'dispatch';
  issueNumber?: number;
  commenterLogin?: string;
}

/**
 * Parse inputs from environment/core
 */
function getInputs(): GeneratorInputs {
  return {
    githubToken: core.getInput('github-token', { required: true }),
    triggerType: (core.getInput('trigger-type') || 'dispatch') as 'comment' | 'dispatch',
    issueNumber: core.getInput('issue-number') ? parseInt(core.getInput('issue-number'), 10) : undefined,
    commenterLogin: core.getInput('commenter-login') || undefined
  };
}

/**
 * Generate a unique branch name with timestamp
 */
function generateBranchName(): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  return `medic/test-conflict-${timestamp}`;
}

/**
 * Generate content for CONFLICT.md that will conflict with main
 */
function generateConflictContent(): string {
  const timestamp = new Date().toISOString();
  return `# The merge conflict will be [${timestamp}]\n# This branch was generated by medic for testing\n`;
}

/**
 * Find the commit to branch from to ensure a merge conflict.
 * Returns the parent of the commit that last modified CONFLICT.md.
 * If CONFLICT.md has only one commit or doesn't exist, returns null.
 */
async function findBranchPoint(
  octokit: OctokitClient,
  owner: string,
  repo: string
): Promise<string | null> {
  try {
    // Get commits that modified CONFLICT.md
    const { data: commits } = await octokit.rest.repos.listCommits({
      owner,
      repo,
      path: CONFLICT_FILE,
      per_page: 2
    });

    if (commits.length < 1) {
      core.warning(`No commits found for ${CONFLICT_FILE}`);
      return null;
    }

    // Get the most recent commit that modified CONFLICT.md
    const lastModifyingCommit = commits[0];
    
    // Get the parent of that commit
    if (!lastModifyingCommit.parents || lastModifyingCommit.parents.length === 0) {
      core.warning('Last modifying commit has no parent (initial commit?)');
      return null;
    }

    const parentSha = lastModifyingCommit.parents[0].sha;
    core.info(`Found branch point: ${parentSha.slice(0, 7)} (parent of ${lastModifyingCommit.sha.slice(0, 7)})`);
    core.info(`  Last CONFLICT.md change: "${lastModifyingCommit.commit.message.split('\n')[0]}"`);
    
    return parentSha;
  } catch (error) {
    core.warning(`Failed to find branch point: ${error instanceof Error ? error.message : String(error)}`);
    return null;
  }
}

/**
 * Create a comment on the triggering issue/PR
 */
async function postComment(
  octokit: OctokitClient,
  owner: string,
  repo: string,
  issueNumber: number,
  body: string
): Promise<void> {
  await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body
  });
}

/**
 * Main function - generates a PR with a merge conflict
 */
export async function run(): Promise<void> {
  const inputs = getInputs();
  const octokit = github.getOctokit(inputs.githubToken);
  const { owner, repo } = github.context.repo;

  core.info('Starting conflict generator...');
  core.info(`Trigger type: ${inputs.triggerType}`);

  try {
    // Step 1: Validate authorization for comment triggers
    if (inputs.triggerType === 'comment') {
      if (!inputs.commenterLogin) {
        core.setFailed('Commenter login is required for comment triggers');
        return;
      }

      if (!isAuthorAllowed(inputs.commenterLogin)) {
        core.info(`User ${inputs.commenterLogin} is not authorized`);
        if (inputs.issueNumber) {
          await postComment(
            octokit,
            owner,
            repo,
            inputs.issueNumber,
            `**Medic:** Sorry @${inputs.commenterLogin}, you are not authorized to generate conflict PRs. Only allowlisted users can use this command.`
          );
        }
        core.setOutput('success', 'false');
        return;
      }
    }

    // Step 2: Find the branch point (parent of last CONFLICT.md change)
    const branchPoint = await findBranchPoint(octokit, owner, repo);
    if (!branchPoint) {
      const errorMsg = `Cannot generate conflict: ${CONFLICT_FILE} needs at least one commit modifying it on main. ` +
        `Please ensure ${CONFLICT_FILE} exists and has been modified at least once.`;
      core.setFailed(errorMsg);
      if (inputs.triggerType === 'comment' && inputs.issueNumber) {
        await postComment(octokit, owner, repo, inputs.issueNumber, `**Medic:** ${errorMsg}`);
      }
      return;
    }

    // Step 3: Generate branch name
    const branchName = generateBranchName();
    core.info(`Branch name: ${branchName}`);

    // Step 4: Configure git
    await exec.exec('git', ['config', 'user.name', 'github-actions[bot]']);
    await exec.exec('git', ['config', 'user.email', 'github-actions[bot]@users.noreply.github.com']);

    // Step 5: Fetch all history and create branch from the branch point
    // We need full history to checkout the older commit
    await exec.exec('git', ['fetch', 'origin', 'main', '--unshallow'], { ignoreReturnCode: true });
    await exec.exec('git', ['fetch', 'origin', 'main']);
    await exec.exec('git', ['checkout', '-b', branchName, branchPoint]);
    core.info(`Created branch from ${branchPoint.slice(0, 7)} (before last ${CONFLICT_FILE} change)`);

    // Step 6: Modify CONFLICT.md with conflicting content
    const conflictContent = generateConflictContent();
    const fs = await import('fs');
    fs.writeFileSync(CONFLICT_FILE, conflictContent);
    core.info(`Modified ${CONFLICT_FILE} with conflicting content`);

    // Step 7: Commit changes
    await exec.exec('git', ['add', CONFLICT_FILE]);
    await exec.exec('git', ['commit', '-m', 'chore: generate test conflict for medic']);

    // Step 8: Push branch
    await exec.exec('git', ['push', 'origin', branchName]);
    core.info(`Pushed branch ${branchName}`);

    // Step 9: Create PR
    const prTitle = `[Medic Test] Conflict PR - ${new Date().toISOString().slice(0, 10)}`;
    const prBody = `## Medic Test PR

This PR was automatically generated by the medic conflict generator.

**Purpose:** Test the medic merge conflict resolution capability.

**How it works:**
- This branch was created from \`${branchPoint.slice(0, 7)}\` (before the last \`${CONFLICT_FILE}\` change on main)
- This branch modifies \`${CONFLICT_FILE}\` with a timestamp value
- The \`main\` branch also has changes to \`${CONFLICT_FILE}\` since the branch point
- This guarantees a merge conflict that medic can attempt to resolve

**Next steps:**
1. Wait for GitHub to detect the merge conflict (may take a few seconds)
2. Use \`/medic: merge conflict\` to trigger resolution
3. Or wait for the scheduled cron job to pick it up

---
*Generated by medic at ${new Date().toISOString()}*`;

    const { data: pr } = await octokit.rest.pulls.create({
      owner,
      repo,
      title: prTitle,
      body: prBody,
      head: branchName,
      base: 'main'
    });

    core.info(`Created PR #${pr.number}: ${pr.html_url}`);

    // Step 10: Comment on triggering issue/PR (if applicable)
    if (inputs.triggerType === 'comment' && inputs.issueNumber) {
      await postComment(
        octokit,
        owner,
        repo,
        inputs.issueNumber,
        `**Medic:** Created test conflict PR #${pr.number} 🔬\n\n` +
        `**Link:** ${pr.html_url}\n\n` +
        `The PR was branched from \`${branchPoint.slice(0, 7)}\` and modifies \`${CONFLICT_FILE}\` to create a merge conflict with \`main\`. ` +
        `Once GitHub detects the conflict (may take a few seconds), you can use \`/medic: merge conflict\` on that PR to test resolution.`
      );
    }

    // Set outputs
    core.setOutput('success', 'true');
    core.setOutput('pr_number', pr.number.toString());
    core.setOutput('pr_url', pr.html_url);
    core.setOutput('branch_name', branchName);

    core.info('Conflict generator completed successfully');

  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    core.error(`Conflict generator failed: ${errorMessage}`);

    // Post failure comment if triggered by comment
    if (inputs.triggerType === 'comment' && inputs.issueNumber) {
      try {
        await postComment(
          octokit,
          owner,
          repo,
          inputs.issueNumber,
          `**Medic:** Failed to generate conflict PR ❌\n\nError: ${errorMessage}`
        );
      } catch {
        // Ignore comment failure
      }
    }

    core.setFailed(errorMessage);
  }
}

// Run when executed directly (not when imported as a module)
const isMainModule = import.meta.url.endsWith(process.argv[1]?.replace(/\\/g, '/') || '');
if (isMainModule || process.env.GITHUB_ACTIONS) {
  run();
}

