name: apidiff-go
description:
  "Uses apidiff CLI to analyze pull requests for breaking changes in a Go
  library's exported symbols."

runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  # path inputs
  directory:
    description: "Directory containing the Go repository"
    required: false
    default: "./"
  go-mod-path:
    description: "Relative path to the go.mod file from the repository root"
    required: false
    default: "."

  # ref inputs
  base-ref:
    description: "Base branch or commit to compare against"
    required: false
    default: "${{ github.event.pull_request.base.ref }}"
  head-ref:
    description: "Head branch or commit to compare against"
    required: false
    default: "${{ github.event.pull_request.head.ref }}"

  # action behaviour inputs
  enforce-compatible:
    description:
      "Enforce that the API changes are compatible. Fails the action if
      incompatible changes are detected."
    required: false
    default: true
