name: manifest-build
description: "Builds all manifest models and uploads them to a specified cache"

inputs:
  # general inputs --------------------------------
  add-packages:
    description:
      "Additional packages to build on top of the declared check packages (space
      separated) - not used if setup-only=true"
    required: false
    default: ""

  # cache inputs ----------------------------------
  cache-url:
    description: "Nix cache URL"
    required: false
    default: ""
  cache-privkey:
    description:
      "Nix cache binary private signing key - not used if setup-only=true"
    required: false
    default: ""

  # grafana inputs (optional) --------------------
  metrics-job-name:
    description: "grafana metrics job name"
    required: false
  metrics-id:
    description:
      "grafana metrics id, used for continuity of metrics during job name
      changes - required if metrics-job-name is passed"
    required: false
  gc-host:
    description: "grafana hostname - required if metrics-job-name is passed"
    required: false
  gc-basic-auth:
    description: "grafana basic auth - required if metrics-job-name is passed"
    required: false
  gc-org-id:
    description:
      "grafana org/tenant id - required if metrics-job-name is passed"
    required: false

runs:
  using: composite
  steps:
    - name: Run check builds
      shell: bash
      run: |
        # run check package builds
        nix flake check
    - name: Build additional packages to cache
      if: inputs.add-packages != '' # only run if there are packages specified
      shell: bash
      run: |
        # builds packages specified in `add-packages` since they may not exist in checks
        PKGS=()
        for key in ${{ inputs.add-packages }}; do
            PKGS+=(".#\"$key\"") # build model name with path - example: .#mf
        done
        nix build --no-link --print-out-paths --verbose --narinfo-cache-negative-ttl 0 ${PKGS[*]}
    - name: Get models from flake check
      shell: bash
      id: getModels
      run: |
        # parse models from the flake check
        PKGS=$(nix flake show --json --allow-import-from-derivation | jq -r '.checks | .[] | keys[]' | sort -u | tr '\n' ' ')
        PKGS+=" ${{ inputs.add-packages }}" # append packages specified by inputs
        echo "pkgs=$PKGS" >> $GITHUB_OUTPUT
    - name: Calculate output + derivation paths
      shell: bash
      id: buildPaths
      run: |
        # calculate output + derivation paths
        PKGS=()
        for key in ${{ steps.getModels.outputs.pkgs }}; do
            PKGS+=(".#\"$key\"") # build model name with path - example: .#mf
        done

        # get runtime output
        PATHS="$(nix derivation show ${PKGS[*]} | jq -r '.[] | .outputs | .[] | .path' | tr '\n' ' ')"

        # # experimental get build time derivation
        # # get build time derivation - does not copy additional build-time dependencies
        # # assumption that other build-time dependencies are available through other nix caches
        # PATHS+=" $(nix derivation show ${PKGS[*]} | jq -r 'keys[]' | tr '\n' ' ')"

        echo "paths=$PATHS" >> $GITHUB_OUTPUT
    - name: Sign all paths locally
      if: inputs.cache-privkey != ''
      shell: bash
      run: |
        # sign paths
        echo "${{ inputs.cache-privkey }}" >> priv.pem
        nix store sign -k priv.pem --verbose ${{ steps.buildPaths.outputs.paths }}
    - name: Copy all paths to bucket
      if: inputs.cache-url != ''
      shell: bash
      run: |
        # push to bucket
        nix copy --verbose --narinfo-cache-positive-ttl 0 --to ${{ inputs.cache-url }} ${{ steps.buildPaths.outputs.paths }}

    - name: Collect metrics
      if: always() && inputs.metrics-job-name != ''
      id: collect-gha-metrics
      uses: smartcontractkit/push-gha-metrics-action@d9da21a2747016b3e13de58c7d4115a3d5c97935 # v3.0.1
      with:
        id: ${{ inputs.metrics-id || inputs.metrics-job-name }}
        basic-auth: ${{ inputs.gc-basic-auth }}
        hostname: ${{ inputs.gc-host }}
        org-id: ${{ inputs.gc-org-id }}
        this-job-name: ${{ inputs.metrics-job-name }}
      continue-on-error: true
