name: devenv-k8s-purge-ns
description: |
  Action to destroy the devenv ephemeral k8s environment.
  It requires running `devenv-k8s-setup-ns` beforehand
  and depends on the environment setup from a dependent composite action.

inputs:
  namespace:
    description: "The devenv namespace that should be destroyed."
    required: true
  gracefully-terminate:
    description:
      "Whether to gracefully terminate the namespace. Defaults to false. If set
      to true, please also provide the termination period."
    required: false
    default: "false"
  gracefully-terminate-period:
    description: |
      "The grace period (in seconds) for gracefully terminating the namespace.
      Default is 0 seconds."
    required: false
    default: "0"

runs:
  using: composite
  steps:
    - name: Tear down devenv ephemeral environment
      if: always()
      shell: bash
      env:
        KUBECACHEDIR: /dev/null
        NAMESPACE: ${{ inputs.namespace }}
        GRACEFULLY_TERMINATE: ${{ inputs.gracefully-terminate }}
        GRACEFULLY_TERMINATE_PERIOD: ${{ inputs.gracefully-terminate-period }}
      run: |
        # Check if the namespace exists
        if kubectl get ns "$NAMESPACE" > /dev/null 2>&1; then
          echo "Namespace $NAMESPACE exists. Proceeding with deletion.."
          kubectl delete ns "$NAMESPACE" --grace-period="$GRACEFULLY_TERMINATE_PERIOD" --wait="$GRACEFULLY_TERMINATE"
        else
          echo "Namespace $NAMESPACE does not exist. Skipping deletion."
        fi
