name: Setup nodejs
description: Setup Nodejs and Pnpm with caching

inputs:
  node-version-file:
    description: The node version
    required: false
    default: .tool-versions
  pnpm-version:
    description: The pnpm version to use
    required: true
    default: ^8.0.0
  use-cache:
    description: Enable github actions cache
    required: true
    default: 'true'
  run-install:
    description: Run npm/yarn/pnpm install
    required: true
    default: 'true'

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: Install pnpm
      uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Get pnpm store directory
      if: inputs.use-cache == 'true'
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      if: inputs.use-cache == 'true'
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Run package manager install
      if: inputs.run-install == 'true'
      shell: bash
      run: pnpm install
