name: Setup nodejs
description: Setup Nodejs and Pnpm with caching

inputs:
  node-version-file:
    description: The node version
    required: false
    default: .tool-versions
  pnpm-version:
    description: The pnpm version to use
    required: true
    default: ^8.0.0
  use-cache:
    description: Enable github actions cache
    required: true
    default: "true"
  run-install:
    description: Run npm/yarn/pnpm install
    required: true
    default: "true"
  package-json-directory:
    description:
      The sub-directory of the package.json, if not at the root of the
      repository
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: Install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Get pnpm store directory
      if: inputs.use-cache == 'true'
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      if: inputs.use-cache == 'true'
      uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Run package manager install
      if: inputs.run-install == 'true'
      shell: bash
      working-directory: ${{ inputs.package-json-directory }}
      run: pnpm install
