name: cicd-build-publish-artifacts
description: Build / publish go artifacts

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  checkout-ref:
    description: "git ref to checkout"
    required: false
    default: ""
  app-name:
    description: ""
    required: false
  publish:
    description: ""
    required: false
    default: "false"
  update-git-tag:
    description: ""
    required: false
    default: "false"
  # aws inputs
  aws-role-duration-seconds:
    description: ""
    required: false
    default: "900"
  aws-region:
    description: ""
    required: false
  aws-account-number:
    description: ""
    required: false
  aws-role-arn:
    description: ""
    required: false
  # docker inputs
  docker-registry:
    description: choices=[local,aws]
    required: false
    default: local
  docker-image-repo:
    description: ""
    required: false
  docker-image-tag:
    description: ""
    required: false
    default: local
  # gati inputs
  use-gati:
    description: ""
    required: false
    default: "false"
  aws-role-arn-gati:
    description: ""
    required: false
  aws-lambda-url-gati:
    description: ""
    required: false
  # golang inputs
  use-go-cache:
    description: ""
    required: false
    default: "false"
  go-cache-dep-path:
    description: ""
    required: false
    default: go.sum
  go-version-file:
    description: ""
    required: false
    default: go.mod
  # goreleaser inputs
  goreleaser-dist:
    description: choices=[goreleaser,goreleaser-pro]
    required: false
    default: goreleaser
  goreleaser-version:
    description: ""
    required: false
    default: latest
  goreleaser-args:
    description: ""
    required: false
  goreleaser-key:
    description: ""
    required: false
  # zig inputs
  use-zig:
    description: ""
    required: false
    default: "false"
  zig-version:
    description: ""
    required: false
    default: "0.10.1"
  # grafana inputs (optional)
  metrics-job-name:
    description: "grafana metrics job name"
    required: false
  metrics-id:
    description:
      "grafana metrics id, used for continuity of metrics during job name
      changes - required if metrics-job-name is passed"
    required: false
  gc-host:
    description: "grafana hostname - required if metrics-job-name is passed"
    required: false
  gc-basic-auth:
    description: "grafana basic auth - required if metrics-job-name is passed"
    required: false
  gc-org-id:
    description:
      "grafana org/tenant id - required if metrics-job-name is passed"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v4.2.1
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}
        ref: ${{ inputs.checkout-ref }}

    - name: Assume aws gati role
      if: inputs.use-gati == 'true'
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: ${{ inputs.aws-role-arn-gati }}
        role-duration-seconds: ${{ inputs.aws-role-duration-seconds }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true

    - name: Get github token from gati
      if: inputs.use-gati == 'true'
      id: get-gh-token
      uses: smartcontractkit/chainlink-github-actions/github-app-token-issuer@main
      with:
        url: ${{ inputs.aws-lambda-url-gati }}

    - name: Configure github token
      if: inputs.use-gati == 'true'
      shell: bash
      run: |
        git config --global \
          url."https://x-access-token:${{ steps.get-gh-token.outputs.access-token }}@github.com/".insteadOf \
          "https://github.com/"

    - name: Setup go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache: ${{ inputs.use-go-cache }}
        cache-dependency-path: ${{ inputs.go-cache-dep-path }}

    - name: Setup zig
      if: inputs.use-zig == 'true'
      uses: goto-bus-stop/setup-zig@7ab2955eb728f5440978d5824358023be3a2802d # v2.2.0
      with:
        version: ${{ inputs.zig-version }}

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

    - name: Set up qemu
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

    - name: Process params
      shell: bash
      id: process-params
      run: |
        if [[ "${{ inputs.docker-registry }}" == "aws" ]]; then
          echo "image-repo=${{ inputs.aws-account-number }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.app-name }}" >> "$GITHUB_OUTPUT"
          echo "aws-account-number=${{ inputs.aws-account-number }}" >> "$GITHUB_OUTPUT"
        else
          echo "image-repo=localhost:5001/${{ inputs.app-name }}" >> "$GITHUB_OUTPUT"
          echo "aws-account-number=not-used" >> "$GITHUB_OUTPUT"
        fi

        if [[ "${{ inputs.use-zig }}" == "true" ]]; then
          echo "zig-exec=$(which zig)" >> "$GITHUB_OUTPUT"
        else
          echo "zig-exec=not-used" >> "$GITHUB_OUTPUT"
        fi

    - name: Configure aws creds
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      if: inputs.publish == 'true' && inputs.docker-registry == 'aws'
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-duration-seconds: ${{ inputs.aws-role-duration-seconds }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true

    - name: Login to aws ecr
      if: inputs.publish == 'true' && inputs.docker-registry == 'aws'
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      with:
        registries: ${{ steps.process-params.outputs.aws-account-number }}

    - name: Update tag
      if: inputs.update-git-tag == 'true'
      uses: richardsimko/update-tag@e173a8ef8f54ab526a91dad6139a25efed62424c # v1.0.11
      with:
        tag_name: v0.0.0-devel
      env:
        GITHUB_TOKEN: ${{ github.token }} # ${{ steps.get-gh-token.outputs.access-token }}

    - name: Run goreleaser release
      uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5.1.0
      with:
        version: ${{ inputs.goreleaser-version }}
        distribution: ${{ inputs.goreleaser-dist }}
        args: release ${{ inputs.goreleaser-args }} --clean
      env:
        IMAGE_REPO: ${{ steps.process-params.outputs.image-repo }}
        IMAGE_TAG: ${{ inputs.docker-image-tag }}
        GORELEASER_KEY: ${{ inputs.goreleaser-key }}
        GITHUB_TOKEN: ${{ github.token }} # ${{ steps.get-gh-token.outputs.access-token }}
        ZIG_EXEC: ${{ steps.process-params.outputs.zig-exec }}

    - name: Collect metrics
      if: always() && inputs.metrics-job-name != ''
      id: collect-gha-metrics
      uses: smartcontractkit/push-gha-metrics-action@d9da21a2747016b3e13de58c7d4115a3d5c97935 # v3.0.1
      with:
        id: ${{ inputs.metrics-id || inputs.metrics-job-name }}
        basic-auth: ${{ inputs.gc-basic-auth }}
        hostname: ${{ inputs.gc-host }}
        org-id: ${{ inputs.gc-org-id}}
        this-job-name: ${{ inputs.metrics-job-name }}
      continue-on-error: true
