name: ci-publish-npm
description: Publishes to NPM

inputs:
  publish-command:
    description: "The command which will be run to publish."
    required: true
  package-json-directory:
    description:
      "The sub directory of the `package.json`. Supply if the publish command
      executes a script declared within the `package.json`, is not located at
      the root of the repository."
    required: false
    default: "."
  github-token:
    description:
      "The `GITHUB_TOKEN` issued for the workflow. Supply when creating Github
      releases. Requires `contents: write` permissions"
    required: false
    default: ${{ github.token }}
  create-github-release:
    description: "Whether or not to create a GitHub release."
    required: false
    default: "false"
  github-release-tag-name:
    description:
      "The name of the GitHub release. Defaults to the current branch name"
    required: false
    default: ${{ github.ref_name }}
  github-release-changelog-path:
    description:
      "The changelog path relative to the root of the repository. Defaults to
      `CHANGELOG.md`"
    required: false
    default: CHANGELOG.md

runs:
  using: composite
  steps:
    # Ensure npm 11.5.1 or later for trusted publishing
    - name: Install npm 11
      shell: bash
      run: |
        npm install --global npm@11
        npm --version

    - name: Publish to NPM
      shell: bash
      working-directory: ${{ inputs.package-json-directory }}
      run: ${{ inputs.publish-command }}

    - name: Create GitHub Release
      if: inputs.create-github-release == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_RELEASE_TAG_NAME: ${{ inputs.github-release-tag-name }}
        GITHUB_RELEASE_CHANGELOG_PATH:
          ${{ inputs.github-release-changelog-path }}
      run: |
        gh release create "${GITHUB_RELEASE_TAG_NAME}" \
          --title "${GITHUB_RELEASE_TAG_NAME}" \
          --notes "View the changelog at [${GITHUB_RELEASE_CHANGELOG_PATH}](${GITHUB_RELEASE_CHANGELOG_PATH})"
