name: flakeguard-ai-analysis
description: "AI Powered Analysis for Flakeguard"

inputs:
  failed_test_results:
    description: The json file from Flakeguard with failed test results
    required: true
  openai_api_key:
    description: The openai api key
    required: true
outputs:
  analysis:
    description: The generated analysis JSONL file
runs:
  using: docker
  image: Dockerfile
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    FAILED_TEST_RESULTS: ${{ inputs.failed_test_results }}
