name: oci-image-bump
description: |
  This action will update the OCI image tag and optionally the image repository
  URL for multiple YAML files.

  It can be invoked via a workflow that might be dispatched from the related
  oci-image-bump-sender composite action.

  Optionally it can close previously opened PR's that match a title regex and
  required labels.

inputs:
  oci-repository-url:
    description: |
      The OCI repository URL to use for the image. If not specified,
      the repository will not be updated.

      Repository URL includes the OCI registry URL and OCI image name.

      Example:
        oci-repository-url: public.ecr.aws/chainlink/chainlink
    required: false
  oci-image-tag:
    description: |
      The tag of the OCI image to update.

      Example:
        oci-image-tag: 'v1.0.0'
    required: true
  paths:
    description: |
      Multi-line CSV for the YAML file paths (supports globbing) and the YAML paths within those files for:

      - OCI repository URL (optional: will leave the current value as-is if not provided)
      - OCI image tag (required)

      File paths (file=) are relative from the root of the git repository.

      Format: file=<file-path>,repository-url-key=<yaml-path>,image-tag-key=<yaml-path>

      Examples:
        paths: |
          file=path/to/config.yaml,repository-url-key=sandbox.main.common.image.repository,image-tag-key=sandbox.main.common.image.tag
          file=path/to/config.yaml,repository-url-key=staging.main.common.image.repository,image-tag-key=staging.main.common.image.tag
          file=path/to/cre-*-config.yaml,repository-url-key=dev.main.common.image.repository,image-tag-key=dev.main.common.image.tag
          file=path/to/another-config.yaml,repository-url-key=prod.main.common.image.repository,image-tag-key=prod.main.common.image.tag
    required: true
  github-token:
    description: |
      The GitHub token to create commits, branches, and PR's.

      Must use a token other than the default workflow token (github.token) in
      order for GHA CI workflows to trigger from the bot-created PR's.

      Will need these permissions:
        - contents: write
        - pull-requests: write
    required: true
  ## start PR Close inputs
  pr-close-enabled:
    description: |
      Whether or not to close previous PR's that match the title regex and
      required labels.

      This is useful to avoid multiple open PR's for the same update.

      If true, the following inputs must be provided and valid:
        - pr-close-title-regex

      And the following are optional:
        - pr-close-exempt-label
        - pr-close-labels
    required: false
    default: "false"
  pr-close-title-regex:
    description: |
      Regular expression to match the title of open PR's to consider for closing.

      Must be true if the pr-close-enabled input is true.

      Needs to be ECMAScript (JS/TS) compatible.

      Example:
        title-regex: '^cre - Deploy nightly-\d{8}$'
    required: false
  pr-close-exempt-label:
    description: |
      Avoid closing PR's that have this label even if the title regex and other labels match.

      Example:
        pr-close-exempt-label: 'do-not-close'
    required: false
  pr-close-labels:
    description: |
      Comma separated list of labels that must be present on an open PR to
      consider it for closing.

      Optional and used in conjunction with the pr-close-title-regex input to
      further refine which PR's to close.

      If multiple labels are provided, it will find any PR with any of the labels.

      Example:
        pr-close-labels: 'preview,image-bump'
    required: false
  ## end PR Close inputs
  pr-base-branch:
    description: "Base branch to create PR against."
    required: false
    default: "main"
  pr-head-branch:
    description: "Head branch to create PR from."
    required: true
  pr-draft:
    description: "Whether or not to create the PR as a draft."
    required: false
    default: "true"
  pr-labels:
    description: |
      Comma separated list of labels to add to the PR.

      Example:
        pr-labels: 'preview-sand,do-not-merge'
    required: false
  pr-title:
    description: "Title of the PR."
    required: true

outputs:
  pr-number:
    description: PR number / ID
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  pr-url:
    description: PR URL
    value: ${{ steps.create-pr.outputs.pull-request-url }}
  pr-operation:
    description: "PR Operation, for ex: created, updated, closed"
    value: ${{ steps.create-pr.outputs.pull-request-operation }}
  pr-head-sha:
    description: Commit SHA of the PR branch
    value: ${{ steps.create-pr.outputs.pull-request-head-sha }}

runs:
  using: composite
  steps:
    - name: Update YAML
      shell: bash
      env:
        OCI_REPOSITORY_URL: ${{ inputs.oci-repository-url }}
        OCI_IMAGE_TAG: ${{ inputs.oci-image-tag }}
        PATHS: ${{ inputs.paths }}
      run: |
        ${GITHUB_ACTION_PATH}/scripts/oci-image-bump.sh

    - name: Check for changes
      id: check-changes
      shell: bash
      run: |
        if ! git diff --quiet; then
          echo "Changes detected, proceeding with PR creation."
        else
          echo "No changes detected after updates. Failing the action."
          exit 1
        fi

    # Commits, creates/pushes branch, and creates the PR.
    - name: Create PR
      id: create-pr
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        base: ${{ inputs.pr-base-branch }}
        branch: ${{ inputs.pr-head-branch }}
        draft: ${{ inputs.pr-draft }}
        labels: ${{ inputs.pr-labels }}
        sign-commits: true
        title: ${{ inputs.pr-title }}
        token: ${{ inputs.github-token }}

    - name: Add PR to Summary
      shell: bash
      env:
        PR_URL: ${{ steps.create-pr.outputs.pull-request-url }}
        PR_NUMBER: ${{ steps.create-pr.outputs.pull-request-number }}
        PR_OPERATION: ${{ steps.create-pr.outputs.pull-request-operation }}
        PR_TITLE: ${{ inputs.pr-title }}
      run: |
        echo "### 🚀 OCI Image Bump Summary" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "📝 **PR** [#${PR_NUMBER} - ${PR_TITLE}](${PR_URL})" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"

    - name: Validate PR Closer Inputs
      if: ${{ inputs.pr-close-enabled == 'true' }}
      shell: bash
      env:
        PR_CLOSE_TITLE_REGEX: ${{ inputs.pr-close-title-regex }}
      run: |
        echo "PR_CLOSE_ENABLED is true, checking required inputs..."
        if [[ -z "${PR_CLOSE_TITLE_REGEX:-}" ]]; then
          echo "PR_CLOSE_TITLE_REGEX is required when PR_CLOSE_ENABLED is true"
          exit 1
        fi

    # Optionally close previously opened PR's for a particular product within
    # an environment.
    - name: PR Closer
      if: ${{ inputs.pr-close-enabled == 'true' }}
      uses: actions/github-script@v7
      env:
        PR_URL: ${{ steps.create-pr.outputs.pull-request-url }}
        PR_NUM: ${{ steps.create-pr.outputs.pull-request-number }}
        PR_CLOSE_EXEMPT_LABEL: ${{ inputs.pr-close-exempt-label }}
        PR_CLOSE_LABELS: ${{ inputs.pr-close-labels }}
        PR_CLOSE_TITLE_REGEX: ${{ inputs.pr-close-title-regex }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prCommentBody = `This PR was closed because there is a newer image bump [PR](${process.env.PR_URL}).`;
          const path = `${process.env.GITHUB_ACTION_PATH}/scripts/pr-closer.js`;
          const run = require(path);
          await run({
            github,
            context,
            core,
            inputs: {
              titleRegex: process.env.PR_CLOSE_TITLE_REGEX,
              requiredLabelsCsv: process.env.PR_CLOSE_LABELS,
              exemptLabel: process.env.PR_CLOSE_EXEMPT_LABEL,
              exemptPrNumbers: [process.env.PR_NUM],
              dryRun: false,
              closeComment: prCommentBody
            }
          });
