name: ci-kubeconform
description: "Kubernetes manifest validation CI check"

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  go-version-file:
    description: "go version file"
    required: false
    default: "go.mod"
  kubeconform-version:
    description: "kubeconform version"
    required: false
    default: "v0.6.4"
  kubernetes-version:
    description: "kubernetes version"
    required: false
    default: "master"
  strict-mode:
    description: "enable strict mode"
    required: false
    default: "true"
  ignore-missing-schemas:
    description: "ignore missing schemas"
    required: false
    default: "true"
  summary:
    description: "enable summary"
    required: false
    default: "true"
  charts-dir:
    description: "charts directory"
    required: true
    default: "charts"
  # grafana inputs
  metrics-job-name:
    description: "grafana metrics job name"
    required: false
    default: ci-kubeconform
  gc-host:
    description: "grafana hostname"
    required: false
  gc-basic-auth:
    description: "grafana basic auth"
    required: false
  gc-org-id:
    description: "grafana org/tenant id"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Install Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: ${{ inputs.go-version-file }}

    - name: Setup yq
      uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f #v1.0.2

    - name: Add helm repos
      shell: bash
      working-directory: ${{ inputs.charts-dir }}
      run: |
        if [[ -f "./Chart.lock" ]]; then
          yq --indent 0 '.dependencies | map(["helm", "repo", "add", .name, .repository] | join(" ")) | .[]' "./Chart.lock"  | sh --;
        fi

    - name: Install kubeconform
      shell: bash
      run: |
        go install github.com/yannh/kubeconform/cmd/kubeconform@${{ inputs.kubeconform-version }}

    - name: Validate Kubernetes manifests
      shell: bash
      env:
        STRICT: "${{ inputs.strict-mode == 'true' && '-strict' || '' }}"
        IGNORE_MISSING_SCHEMAS:
          "${{ inputs.ignore-missing-schemas == 'true' &&
          '-ignore-missing-schemas' || '' }}"
        SUMMARY: "${{ inputs.summary == 'true' && '-summary' || '' }}"
      working-directory: ${{ inputs.charts-dir }}
      run: |
        helm dependency build
        helm template . | kubeconform -kubernetes-version ${{ inputs.kubernetes-version }} ${{ env.STRICT }} ${{ env.IGNORE_MISSING_SCHEMAS }} ${{ env.SUMMARY }}

    - name: Collect metrics
      if: always()
      id: collect-gha-metrics
      uses: smartcontractkit/push-gha-metrics-action@e34ae8a4df60f4d9fdef1e32a69747bab130840e # v2.2.0
      with:
        basic-auth: ${{ inputs.gc-basic-auth }}
        hostname: ${{ inputs.gc-host }}
        org-id: ${{ inputs.gc-org-id}}
        this-job-name: ${{ inputs.metrics-job-name }}
      continue-on-error: true
