name: Promote image between ECR registries
description: |
  Promote an image from one ECR registry to another, using cosign (default) or skopeo.
  The action will assume the provided IAM roles to access the source and destination registries.

inputs:
  aws-region:
    description:
      "AWS region for BOTH registries. Use source_aws_region and
      destination-aws-region instead."
    required: false
  source-aws-region:
    description:
      "AWS region for source registry. Example: eu-west-1. Falls back to
      aws-region if not provided."
    required: false
  destination-aws-region:
    description:
      "AWS region for destination registry. Example: us-east-1. Falls back to
      aws-region if not provided."
    required: false
  source-role-arn:
    description:
      "IAM Role ARN to assume in SOURCE account (needs ECR read permissions)"
    required: true
  destination-role-arn:
    description:
      IAM Role ARN to assume in DEST account (needs ECR write permissions)
    required: true
  source-registry:
    description:
      Source registry host, e.g. 111111111111.dkr.ecr.eu-west-1.amazonaws.com
    required: true
  destination-registry:
    description:
      Destination registry host, e.g.
      222222222222.dkr.ecr.eu-west-1.amazonaws.com
    required: true
  source-repository:
    description:
      Source repository name, e.g. my-app (not required if using images matrix)
    required: false
  destination-repository:
    description:
      Destination repository name, e.g. my-app (not required if using images
      matrix)
    required: false
  source-tag:
    description:
      Source tag (or digest if you use @sha256:... in advanced mode) (not
      required if using images matrix)
    required: false
  destination-tag:
    description: Destination tag (not required if using images matrix)
    required: false
  images:
    description: |
      JSON array of images to promote. Each object should have: sourceRepository, destinationRepository, sourceTag, destinationTag.
      Example: [{"sourceRepository":"app1","destinationRepository":"app1","sourceTag":"v1.0","destinationTag":"v1.0"}]
      If provided, this takes precedence over individual sourceRepository/destinationRepository/sourceTag/destinationTag inputs.
    required: false
    default: ""
  copy-signatures:
    description:
      Use cosign to copy images (includes signatures and attestations). Set to
      'false' to use skopeo instead.
    required: false
    default: "true"

outputs:
  promoted-images:
    description:
      JSON array of promoted images with their source and destination details,
      promotion duration, and status.
    value: ${{ steps.promoted-images.outputs.promoted-images }}

runs:
  using: "composite"
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
      with:
        cosign-release: "v3.0.2"

    - name: Configure AWS credentials (SOURCE)
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
      with:
        role-to-assume: ${{ inputs.source-role-arn }}
        aws-region: ${{ inputs.source-aws-region || inputs.aws-region }}

    - name: Login to Amazon ECR (SOURCE)
      id: src
      uses: aws-actions/amazon-ecr-login@v2

    - name: Configure AWS credentials (DESTINATION)
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
      with:
        role-to-assume: ${{ inputs.destination-role-arn }}
        aws-region: ${{ inputs.destination-aws-region || inputs.aws-region }}

    - name: Login to Amazon ECR (DESTINATION)
      id: dst
      uses: aws-actions/amazon-ecr-login@v2

    - name: Copy image
      shell: bash
      env:
        SOURCE_REGISTRY: ${{ inputs.source-registry }}
        DESTINATION_REGISTRY: ${{ inputs.destination-registry }}
        SOURCE_REPOSITORY: ${{ inputs.source-repository }}
        DESTINATION_REPOSITORY: ${{ inputs.destination-repository }}
        SOURCE_TAG: ${{ inputs.source-tag }}
        DESTINATION_TAG: ${{ inputs.destination-tag }}
        IMAGES_JSON: ${{ inputs.images }}
        SKOPEO_ARGS: ${{ inputs.skopeo-additional-args }}
        SOURCE_AWS_REGION: ${{ inputs.source-aws-region || inputs.aws-region }}
        DESTINATION_AWS_REGION:
          ${{ inputs.destination-aws-region || inputs.aws-region }}
        SRC_PASS: ${{ steps.src.outputs.password }}
        DST_PASS: ${{ steps.dst.outputs.password }}
        COPY_SIGNATURES: ${{ inputs.copy-signatures }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        "${ACTION_PATH}/scripts/promote-images.sh"

    - name: Generate Job Summary
      if: always()
      shell: bash
      run: |
        if [ -f /tmp/promotion-results/promotion-summary.md ]; then
          cat /tmp/promotion-results/promotion-summary.md >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload Promotion Results
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: promotion-results-${{ github.run_id }}
        path: /tmp/promotion-results/
        retention-days: 30

    - name: Set output promoted-images
      id: promoted-images
      if: always()
      shell: bash
      run: |
        if [ -f /tmp/promotion-results/promoted-images.json ]; then
          echo "promoted-images=$(cat /tmp/promotion-results/promoted-images.json)" >> $GITHUB_OUTPUT
        else
          echo "promoted-images=[]" >> $GITHUB_OUTPUT
        fi
