name: Promote image between ECR registries
description: |
  Promote an image from one ECR registry to another, using skopeo under the hood.
  The action will assume the provided IAM roles to access the source and destination registries.

inputs:
  aws_region:
    description:
      "AWS region for BOTH registries. Use source_aws_region and
      destination_aws_region instead."
    required: false
  source_aws_region:
    description:
      "AWS region for source registry. Example: eu-west-1. Falls back to
      aws_region if not provided."
    required: false
  destination_aws_region:
    description:
      "AWS region for destination registry. Example: us-east-1. Falls back to
      aws_region if not provided."
    required: false
  source_role_arn:
    description:
      "IAM Role ARN to assume in SOURCE account (needs ECR read permissions)"
    required: true
  destination_role_arn:
    description:
      IAM Role ARN to assume in DEST account (needs ECR write permissions)
    required: true
  source_registry:
    description:
      Source registry host, e.g. 111111111111.dkr.ecr.eu-west-1.amazonaws.com
    required: true
  destination_registry:
    description:
      Destination registry host, e.g.
      222222222222.dkr.ecr.eu-west-1.amazonaws.com
    required: true
  source_repository:
    description:
      Source repository name, e.g. my-app (not required if using images matrix)
    required: false
  destination_repository:
    description:
      Destination repository name, e.g. my-app (not required if using images
      matrix)
    required: false
  source_tag:
    description:
      Source tag (or digest if you use @sha256:... in advanced mode) (not
      required if using images matrix)
    required: false
  destination_tag:
    description: Destination tag (not required if using images matrix)
    required: false
  images:
    description: |
      JSON array of images to promote. Each object should have: source_repository, destination_repository, source_tag, destination_tag.
      Example: [{"source_repository":"app1","destination_repository":"app1","source_tag":"v1.0","destination_tag":"v1.0"}]
      If provided, this takes precedence over individual source_repository/destination_repository/source_tag/destination_tag inputs.
    required: false
    default: ""
  skopeo_additional_args:
    description:
      Extra args for skopeo copy (e.g. "--all" to copy multi-arch lists)
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install skopeo and jq
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo jq

    - name: Configure AWS credentials (SOURCE)
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
      with:
        role-to-assume: ${{ inputs.source_role_arn }}
        aws-region: ${{ inputs.source_aws_region || inputs.aws_region }}

    - name: Get SOURCE ECR login password
      id: src
      shell: bash
      env:
        REGION: ${{ inputs.source_aws_region || inputs.aws_region }}
      run: |
        set -euo pipefail
        PASS=$(aws ecr get-login-password)
        echo "::add-mask::$PASS"
        echo "password=$PASS" >> "$GITHUB_OUTPUT"

    - name: Configure AWS credentials (DESTINATION)
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
      with:
        role-to-assume: ${{ inputs.destination_role_arn }}
        aws-region: ${{ inputs.destination_aws_region || inputs.aws_region }}

    - name: Get DESTINATION ECR login password
      id: dst
      shell: bash
      env:
        REGION: ${{ inputs.destination_aws_region || inputs.aws_region }}
      run: |
        set -euo pipefail
        PASS=$(aws ecr get-login-password)
        echo "::add-mask::$PASS"
        echo "password=$PASS" >> "$GITHUB_OUTPUT"

    - name: Copy image with skopeo
      shell: bash
      env:
        SOURCE_REGISTRY: ${{ inputs.source_registry }}
        DESTINATION_REGISTRY: ${{ inputs.destination_registry }}
        SOURCE_REPOSITORY: ${{ inputs.source_repository }}
        DESTINATION_REPOSITORY: ${{ inputs.destination_repository }}
        SOURCE_TAG: ${{ inputs.source_tag }}
        DESTINATION_TAG: ${{ inputs.destination_tag }}
        IMAGES_JSON: ${{ inputs.images }}
        SKOPEO_ARGS: ${{ inputs.skopeo_additional_args }}
        SOURCE_AWS_REGION: ${{ inputs.source_aws_region || inputs.aws_region }}
        DESTINATION_AWS_REGION:
          ${{ inputs.destination_aws_region || inputs.aws_region }}
        SRC_PASS: ${{ steps.src.outputs.password }}
        DST_PASS: ${{ steps.dst.outputs.password }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        "${ACTION_PATH}/scripts/promote-images.sh"

    - name: Generate Job Summary
      if: always()
      shell: bash
      run: |
        if [ -f /tmp/promotion-results/promotion-summary.md ]; then
          cat /tmp/promotion-results/promotion-summary.md >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload Promotion Results
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: promotion-results-${{ github.run_id }}
        path: /tmp/promotion-results/
        retention-days: 30
