name: "Schema Validator Action"
description: "Validates schema compatibility with schema registry"

inputs:
  docker-registry:
    description: "Docker registry to use"
    required: true
    default: "aws"
  image-tag:
    description: "Image tag to use"
    required: false
    default: "latest"
  # aws inputs
  aws-role-duration-seconds:
    description: ""
    required: false
    default: "900"
  aws-region:
    description: ""
    required: false
  aws-account-number:
    description: ""
    required: false
  aws-role-arn:
    description: ""
    required: false

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4.2.1
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}
    - name: Detect changed files
      id: changes
      shell: bash
      run:
        echo "CHANGED_FILES=$(git diff --name-only ${{
        github.event.repository.default_branch }})" >> $GITHUB_ENV
    - name: Start Redpanda with Docker Compose
      shell: bash
      run: |
        docker compose -f "${{ github.action_path }}/docker-compose.yml" up -d redpanda-console
    - name: Configure aws creds
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      if: inputs.docker-registry == 'aws'
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-duration-seconds: ${{ inputs.aws-role-duration-seconds }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true
    - name: Login to aws ecr
      if: inputs.docker-registry == 'aws'
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      with:
        registries: "123456789012,998877665544"
    - name: Pull schema-validator image from ECR
      shell: bash
      run: |
        docker pull ${{ steps.login-ecr.outputs.registry }}/atlas-beholder-schema-validator:${{ inputs.image-tag }}
    - name: Run Schema Validator
      shell: bash
      run: |
        docker run -v "$PWD:/app/repo" \
        --network redpanda_network \
        -e SCHEMA_REGISTRY_URL=http://redpanda:8081 \
        atlas-beholder-schema-validator:latest \
        --config-file /app/repo/config.yaml
    - name: Validate schemas in master branch
      shell: bash
      run: |
        # Store current branch
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

        # Checkout and validate default branch
        git checkout ${{ github.event.repository.default_branch }}, 
        docker run -v "$PWD:/app/repo" \
        --network redpanda_network \
        -e SCHEMA_REGISTRY_URL=http://redpanda-0:8081 \
        atlas-beholder-schema-validator:latest \
        validate --phase master

        # Return to original branch
        git checkout $CURRENT_BRANCH

    - name: Validate schemas in current branch
      shell: bash
      run: |
        docker run -v "$PWD:/app/repo" \
        --network redpanda_network \
        -e SCHEMA_REGISTRY_URL=http://redpanda:8081 \
        -e CHANGED_FILES="$CHANGED_FILES" \
        atlas-beholder-schema-validator:latest \
        validate --phase pr
