name: install-nix
description:
  "Install Nix using DeterminateSystems/nix-installer-action by default, with an
  option for a custom install URL"

inputs:
  install-url:
    description:
      "Custom URL for Nix installer (default uses DeterminateSystems installer)"
    required: false
    default: ""

  extra-conf:
    description: "Additional Nix configuration options"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install Nix
      if: ${{ inputs.install-url == '' }}
      uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
      with:
        determinate: true
        extra-conf: |
          sandbox = relaxed
          ${{ inputs.extra-conf }}

    - name: Install Nix with Custom URL
      if: ${{ inputs.install-url != '' }}
      shell: bash
      run: |
        echo "Installing Nix from custom URL: ${{ inputs.install-url }}"
        curl -L ${{ inputs.install-url }} | sh

        # Apply extra configuration if provided
        if [ -n "${{ inputs.extra-conf }}" ]; then
          echo "${{ inputs.extra-conf }}" >> /etc/nix/nix.conf
        fi

    - name: Verify Nix Installation
      shell: bash
      run: |
        nix --version
