name: slack-notify-git-ref
description: "Notify slack about git ref (tag or branch)"

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  # slack inputs
  slack-channel-id:
    description: "slack channel id to send the alert to"
    required: true
  slack-bot-token:
    description:
      "slack bot api token - the token requires `chat:write` permission"
    required: true
  # custom inputs
  git-ref:
    description: "git ref to notify slack about"
    required: true
  git-ref-type:
    description: "git ref type. valid inputs: tag, branch"
    required: true
  docker-image-name:
    description: |
      Deprecated: use docker-image-names instead.
      Optional docker image name with tag (single image).

      Example: `public.ecr.aws/smartcontractkit/chainlink:v1.2.3`
    required: false
  docker-image-digest:
    description: |
      Deprecated: use docker-image-names instead.
      Optional docker image digest (single image).

      Example: `sha256:1234567890abcdef`
    required: false
  docker-image-names:
    description: |
      Optional multi-line string of docker image names with their digests.
      Each line should be in the format: `image_name|digest`

      Example:
        public.ecr.aws/chainlink/ccip:2.34.1-ccip-beta.3|sha256:5f218f...
        public.ecr.aws/chainlink/chainlink:2.34.1-beta.3|sha256:b48d5b...
    required: false
  changelog-url:
    description: "URL for CHANGELOG to include in Slack message"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}
    - name: Validate inputs
      shell: bash
      env:
        GIT_REF_TYPE: ${{ inputs.git-ref-type }}
      run: |
        if [[ "${GIT_REF_TYPE:-}" != "tag" && "${GIT_REF_TYPE:-}" != "branch" ]]; then
          echo "::error::invalid inputs.git-ref-type: ${{ inputs.git-ref-type }}. Must be either 'tag' or 'branch'."
          exit 1
        fi

    - name: Render and update payload template
      shell: bash
      id: update-payload
      env:
        DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
        DOCKER_IMAGE_DIGEST: ${{ inputs.docker-image-digest }}
        DOCKER_IMAGE_NAMES: ${{ inputs.docker-image-names }}
        CHANGELOG_URL: ${{ github.inputs.changelog-url }}
        GIT_REF_NAME: ${{ inputs.git-ref }}
        GITHUB_RUN_URL: >-
          ${{
            format(
              'https://github.com/{0}/actions/runs/{1}',
              github.repository,
              github.run_id
            )
          }}
        PATH_TO_PAYLOAD: ${{ github.action_path }}/payload.json
      run: |
        envsubst < "${PATH_TO_PAYLOAD}" | tee payload_temp.json

        # Build the docker images field value.
        # Supports multi-line docker-image-names input and falls back
        # to the legacy single docker-image-name / docker-image-digest inputs.
        docker_lines=""

        if [[ -n "${DOCKER_IMAGE_NAMES:-}" ]]; then
          while IFS= read -r line; do
            # skip empty lines
            [[ -z "${line}" ]] && continue
            img_name="${line%%|*}"
            img_digest="${line#*|}"
            if [[ -n "${img_digest}" && "${img_digest}" != "${img_name}" ]]; then
              docker_lines+="\`${img_name}\` (\`${img_digest}\`)\n"
            else
              docker_lines+="\`${img_name}\`\n"
            fi
          done <<< "${DOCKER_IMAGE_NAMES}"
        elif [[ -n "${DOCKER_IMAGE_NAME:-}" ]]; then
          if [[ -n "${DOCKER_IMAGE_DIGEST:-}" ]]; then
            docker_lines="\`${DOCKER_IMAGE_NAME}\` (\`${DOCKER_IMAGE_DIGEST}\`)"
          else
            docker_lines="\`${DOCKER_IMAGE_NAME}\`"
          fi
        fi

        if [[ -n "${docker_lines}" ]]; then
          # Remove any trailing newline
          docker_lines="$(echo -e "${docker_lines}" | sed '/^$/d')"
          jq --arg images "${docker_lines}" \
            '.attachments[0].fields += [{"title": "Docker Image Names", "value": $images, "short": false}]' \
            payload_temp.json > payload_temp2.json
          mv payload_temp2.json payload_temp.json
        fi

        if [[ -n "${CHANGELOG_URL:-}" ]]; then
          jq --arg changelog "\`${CHANGELOG_URL}\`" \
            '.attachments[0].fields += [{"title": "CHANGELOG URL", "value": $changelog, "short": false}]' \
            payload_temp.json > payload_temp2.json
          mv payload_temp2.json payload_temp.json
        fi

        cat payload_temp.json
        {
          echo 'payload<<EOF'
          cat payload_temp.json
          echo 'EOF'
        } >> $GITHUB_ENV

    - name: Notify slack
      uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
      with:
        payload: ${{ env.payload }}
        channel-id: ${{ inputs.slack-channel-id }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
