name: free-disk-space
description: "Delete specific directories or files to free disk space"

inputs: {}

runs:
  using: composite
  steps:
    - name: Free Disk Space (fast)
      shell: bash
      run: |
        set -Eeuo pipefail
        shopt -s nullglob dotglob

        PATHS=(
          /usr/share/dotnet
          /usr/local/lib/android
          /usr/local/share/powershell
          /usr/local/share/chromium
          /usr/local/lib/heroku
          /usr/local/share/boost
          /usr/local/share/miniconda
          /opt/hostedtoolcache/CodeQL
          /opt/hostedtoolcache/Ruby
          /usr/lib/jvm
          /opt/hostedtoolcache/Java_*
          /opt/microsoft
          /opt/google
        )

        echo "Starting disk cleanup..."
        sudo rm -rf -- "${PATHS[@]}" 2>/dev/null || true
        echo "Disk cleanup complete."
