name: crib-purge-environment
description: |
  Action to destroy CRIB epehemeral environment.
  It requires to run crib-deployment-environment beforehand
  and depends on the environment setup from a dependent composite action.

inputs:
  namespace:
    description: "The CRIB namespace that should be destroyed."
    required: true

runs:
  using: composite
  steps:
    - name: Tear down CRIB ephemeral environment
      if: always()
      shell: bash
      env:
        KUBECACHEDIR: /dev/null
      run: |
        NAMESPACE="${{ inputs.namespace }}"

        # Check if the namespace exists
        if kubectl get ns "$NAMESPACE" > /dev/null 2>&1; then
          echo "Namespace $NAMESPACE exists. Proceeding with deletion.."
          kubectl delete ns "$NAMESPACE" --grace-period=0 --wait=false
        else
          echo "Namespace $NAMESPACE does not exist. Skipping deletion."
        fi
