name: ctf-setup-run-tests-environment
description: "Common test env setup for CTF"

inputs:
  test_download_vendor_packages_command:
    required: false
    description: The command to download the go modules
    default: make download
  go_version:
    required: false
    description: Go version to install
  go_mod_path:
    required: false
    description: The go.mod file path
    default: "go.mod"
  go_necessary:
    required: false
    description:
      Whether to install go, should be true unless you already have a test
      binary
    default: "true"
  cache_restore_only:
    required: false
    description:
      Only restore the cache, set to true if you want to restore and save on
      cache hit miss
    default: "false"
  cache_key_id:
    required: false
    description: Cache go vendors unique id
    default: go
  aws_registries:
    required: false
    description: AWS registries to log into for the test if needed
  aws_role_duration_seconds:
    required: false
    default: "3600"
    description: The duration to be logged into the aws role for
  dockerhub_username:
    description:
      Username for Docker Hub to avoid rate limits when pulling public images
    required: false
  dockerhub_password:
    description:
      Password for Docker Hub to avoid rate limits when pulling public images
    required: false
  QA_AWS_REGION:
    required: true
    description: The AWS region to use
  QA_AWS_ROLE_TO_ASSUME:
    required: true
    description: The AWS role to assume
  should_tidy:
    required: false
    description: Should we check go mod tidy
    default: "true"
  no_cache:
    required: false
    description: Do not use a go cache
    default: "false"
  gati_token:
    required: false
    description: Token provided by GATI to pull from private repos
  enable-gap:
    required: false
    default: "true"
    description: Configure and enable GAP for accessing internal services.
  main-dns-zone:
    required: false
    default: ""
    description:
      The primary DNS zone used in the hostname of the Kubernetes API endpoint.
      Required if GAP is enabled.
  k8s-cluster-name:
    required: false
    default: ""
    description:
      The name of the Kubernetes cluster to be used in the `kubectl`
      configuration for accessing the desired cluster.
  enable-proxy-debug:
    description:
      "Enable or disable detailed Envoy proxy logs used for K8s API access. When
      enabled, debug logs are generated locally, and container logs are streamed
      to the console for troubleshooting."
    required: false
    default: "false"
  prod_aws_region:
    required: false
    description: The AWS region to use for prod ECR
  prod_aws_role_to_assume:
    required: false
    description: The AWS role to assume for prod ECR
  gauntlet_plus_plus_image:
    required: false
    description: Gauntlet-plus-plus image link
  prod_aws_account_number:
    required: false
    description: AWS Account number that holds the gauntlet_plus_plus
  install_plugins_public:
    required: false
    default: "false"
    description: "Set to true to install the public LOOP plugins"
  aptos_cli_version:
    required: false
    default: ""
    description: "Set to an Aptos CLI version to install (e.g. 7.2.0, latest)"
  sui_cli_version:
    required: false
    default: ""
    description:
      "Set to a Sui CLI version to install (e.g. mainnet-v1.50.1, mainnet"
  setup_db:
    required: false
    default: "false"
    description: "Set to true to setup the database for the tests"

outputs:
  database_url:
    description: The database URL for the tests
    value: ${{ steps.setup-pg.outputs.database-url }}

runs:
  using: composite
  steps:
    - name: Validate GAP inputs
      shell: bash
      if: inputs.enable-gap == 'true'
      run: |
        if [ -z "${{ inputs.main-dns-zone }}" ]; then
          echo "Error: main-dns-zone is required when enable-gap is true."
          exit 1
        fi
        if [ -z "${{ inputs.k8s-cluster-name }}" ]; then
          echo "Error: k8s-cluster-name is required when enable-gap is true."
          exit 1
        fi

    # Go setup and caching
    - name: Setup Go
      if: inputs.go_necessary == 'true'
      uses: smartcontractkit/.github/actions/ctf-setup-go@8fb84214197a54beaf10afd4fdb258f74b41de1a # ctf-setup-go@0.2.0
      with:
        go_version: ${{ inputs.go_version }}
        go_mod_path: ${{ inputs.go_mod_path }}
        cache_restore_only: ${{ inputs.cache_restore_only }}
        cache_key_id: ${{ inputs.cache_key_id }}
        should_tidy: ${{ inputs.should_tidy }}
        no_cache: ${{ inputs.no_cache }}
        test_download_vendor_packages_command:
          ${{ inputs.test_download_vendor_packages_command }}
        gati_token: ${{ inputs.gati_token }}

    - name: Setup postgres container
      id: setup-pg
      if: inputs.setup_db == 'true'
      uses: smartcontractkit/.github/actions/setup-postgres@setup-postgres/v1
      with:
        tmpfs: true

    - name: Setup database
      if: inputs.setup_db == 'true'
      shell: bash
      env:
        CL_DATABASE_URL: ${{ steps.setup-pg.outputs.database-url }}
      run: |
        go run ./core/store/cmd/preparetest

    - name: Setup gauntlet plus plus
      if: inputs.gauntlet_plus_plus_image
      uses: smartcontractkit/.github/actions/pull-private-ecr-image@pull-private-ecr-image/1.0.0 # pull-private-ecr-image@1.0.0
      with:
        aws-region: ${{ inputs.prod_aws_region }}
        aws-role-arn: ${{ inputs.prod_aws_role_to_assume }}
        image-url: ${{ inputs.gauntlet_plus_plus_image }}
        aws-account-number: ${{ inputs.prod_aws_account_number }}

    - name: Install LOOP Plugins
      if: inputs.install_plugins_public == 'true'
      shell: bash
      run: |
        make install-loopinstall
        make install-plugins-public

    - name: Install Aptos CLI
      if: inputs.aptos_cli_version
      uses: aptos-labs/actions/install-aptos-cli@63740b290d839b87ecfafbcf75ed03a36a54a29f # jan 15, 2025
      with:
        CLI_VERSION: ${{ inputs.aptos_cli_version }}

    - name: Install Sui CLI
      if: inputs.sui_cli_version
      uses: smartcontractkit/chainlink-sui/.github/actions/setup-sui@4b810a59d905f512d3c989f5291f969f6fc69eb2 # 30-09-2025
      with:
        version: ${{ inputs.sui_cli_version }}

    # Setup AWS cred and K8s context
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
      with:
        aws-region: ${{ inputs.QA_AWS_REGION }}
        role-to-assume: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: ${{ inputs.aws_role_duration_seconds }}
        mask-aws-account-id: true

    - name: Configure local GAP proxy for accessing (Kubernetes) services
      uses: smartcontractkit/.github/actions/setup-gap@8fb84214197a54beaf10afd4fdb258f74b41de1a # setup-gap@4.0.1
      if: inputs.enable-gap == 'true'
      with:
        aws-region: ${{ inputs.QA_AWS_REGION }}
        aws-role-arn: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
        aws-role-duration-seconds: 3600 # 1 hour
        gap-name: k8s
        k8s-cluster-name: ${{ inputs.k8s-cluster-name }}
        main-dns-zone: ${{ inputs.main-dns-zone }}
        proxy-port: 9339
        use-k8s: true
        enable-proxy-debug: ${{ inputs.enable-proxy-debug }}

    # Login to AWS ECR registries if needed
    - name: Login to Amazon ECR
      if: inputs.aws_registries && inputs.QA_AWS_REGION
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      with:
        registries: ${{ inputs.aws_registries }}
      env:
        AWS_REGION: ${{ inputs.QA_AWS_REGION }}

    # To avoid rate limiting from Docker Hub, we can login with a paid user account.
    - name: Login to Docker Hub
      if: inputs.dockerhub_username && inputs.dockerhub_password
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}

    # Helm Setup
    - uses: azure/setup-helm@29960d0f5f19214b88e1d9ba750a9914ab0f1a2f # v4.0.0
      with:
        version: v3.13.1
    - name: Add required helm charts including chainlink-qa
      shell: bash
      run: |
        helm repo add bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
        helm repo add chainlink-qa https://raw.githubusercontent.com/smartcontractkit/qa-charts/gh-pages/

    # Display tool versions
    - name: Tool Versions
      shell: bash
      run: |
        go version
        aws --version
        helm version
        helm repo list
