# Fails when:
# - vulnerabilities are found in the dependency tree with specified severity or grater
vulnerability_check: true
fail_on_severity: "moderate" # low, moderate, high, critical
license_check: false
