name: ci-lint-charts
description: Lint helm charts

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  # chart-testing inputs
  chart-testing-config-path:
    description: "chart-testing config path"
    required: false
    default: .ct.yml
  chart-testing-extra-args:
    description: "chart-testing extra args"
    required: false
    default: ""
  charts-dir:
    description: "charts directory"
    required: false
    default: "charts"

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Setup yq
      uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f #v1.0.2

    - name: Add helm repos
      shell: bash
      working-directory: ${{ inputs.charts-dir }}
      run: |
        if [[ -f "./Chart.lock" ]]; then
          yq --indent 0 '.dependencies | map(["helm", "repo", "add", .name, .repository] | join(" ")) | .[]' "./Chart.lock"  | sh --;
        fi

    - name: Set up chart-testing
      uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

    - name: Run chart-testing (lint)
      shell: bash
      env:
        CHART_TESTING_CONFIG_PATH: ${{ inputs.chart-testing-config-path }}
        CHART_TESTING_EXTRA_ARGS: ${{ inputs.chart-testing-extra-args }}
      run: |
        ct lint --config "${CHART_TESTING_CONFIG_PATH}" "${CHART_TESTING_EXTRA_ARGS}"
