name: cicd-build-publish-artifacts
description: Build / publish typescript artifacts

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  publish-release:
    description: ""
    required: false
    default: "false"
  setup-qemu:
    description: ""
    required: false
    default: "false"
  release-assets:
    description: ""
    required: false
    default: "bin/*"
  extra-build-args:
    description: ""
    required: false
    default: ""
  extra-package-args:
    description: ""
    required: false
    default: ""
  # monorepo inputs
  publish-monorepo-release:
    description: ""
    required: false
    default: "false"
  monorepo-release-dir:
    description: ""
    required: false
    default: "packages"
  monorepo-release-name:
    description: ""
    required: false
  monorepo-release-version:
    description: ""
    required: false
  # nodejs inputs
  node-version-file:
    description: ""
    required: false
    default: ".tool-versions"
  pnpm-version:
    description: ""
    required: false
    default: "^10.0.0"
  # foundry inputs
  setup-foundry:
    description: ""
    required: false
    default: "false"
  foundry-version:
    description: ""
    required: false
    default: nightly

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Setup nodejs
      uses: smartcontractkit/.github/actions/setup-nodejs@main
      with:
        node-version-file: ${{ inputs.node-version-file }}
        pnpm-version: ${{ inputs.pnpm-version }}
        use-cache: "true"
        run-install: "true"
      continue-on-error: true

    - name: Set up qemu
      if: inputs.setup-qemu == 'true'
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

    - name: Setup foundry
      if: inputs.setup-foundry == 'true'
      uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1.7.0
      with:
        version: ${{ inputs.foundry-version }}

    - name: Run build
      shell: bash
      run: pnpm run build ${{ inputs.extra-build-args }}

    - name: Run package
      shell: bash
      run: pnpm run package ${{ inputs.extra-package-args }}

    - name: Prep release cmd
      if: inputs.publish-release == 'true'
      shell: bash
      run: pnpm run prep:dev:release

    - name: Upload artifacts to release
      if: inputs.publish-release == 'true'
      uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
      with:
        repo_token: ${{ github.token }}
        file: ${{ inputs.release-assets }}
        tag: ${{ inputs.release-version }}
        overwrite: true
        file_glob: true

    - name: Upload artifacts to monorepo release
      if: inputs.publish-monorepo-release == 'true'
      uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # 2.11.3
      with:
        repo_token: ${{ github.token }}
        file:
          ${{ inputs.monorepo-release-dir }}/${{ inputs.monorepo-release-name
          }}/${{ inputs.release-assets }}
        tag:
          ${{ inputs.monorepo-release-name }}@${{
          inputs.monorepo-release-version }}
        overwrite: true
        file_glob: true
