name: license-checker
description:
  "Check for restricted licenses. A wrapper for
  [LicenseFinder](https://github.com/pivotal/LicenseFinder)"

inputs:
  # specific inputs
  license-finder-custom-args:
    description: "custom args to pass to license_finder"
    required: false
    default: |
      --recursive \
      --quiet
  license-finder-version:
    description: "license_finder version"
    required: false
    default: "7.2.1"
  working-directory:
    description: "working directory for license_finder"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: "Install license-finder"
      run: |
        sudo gem install license_finder -v ${{ inputs.license-finder-version }} --silent
      shell: bash
    - name: Run license-finder
      working-directory: ${{ inputs.working-directory }}
      run: |
        license_finder --decisions-file=${{ github.action_path }}/doc/dependency_decisions.yml ${{ inputs.license-finder-custom-args }}
      shell: bash
