name: cicd-build-push-docker-manifest
description: |
  Reusable action to create docker manifest for multi-platform. Use this after
  the `cicd-build-push-docker` action to create and push the manifest.
inputs:
  cosign-oidc-identity:
    description:
      "OIDC issuer for cosign. Example:
      https://github.com/smartcontractkit/chainlink/.github/workflows/build-publish.yml@${{
      github.ref }}"
    required: false
  cosign-oidc-issuer:
    description: "OIDC issuer for cosign"
    required: false
    default: "https://token.actions.githubusercontent.com"
  docker-manifest-name:
    required: true
    description: |
      Name of the Docker manifest including hostname. Excludes any tags.

      Example:
        public.ecr.aws/chainlink/chainlink
  docker-manifest-sign:
    required: false
    description: "Sign the docker manifest"
    default: "true"
  docker-manifest-tag:
    required: true
    description: "Tag for the docker manifest"
  docker-image-name-digests:
    required: true
    description: |
      Docker image names plus their digests which will become added to this
      manifest. Comma separated list.

      Example:
        public.ecr.aws/chainlink/chainlink@sha256:abc123,public.ecr.aws/chainlink/chainlink@sha256:def456
  context:
    description:
      "Build's context is the set of files located in the specified PATH or URL"
    required: false
  # aws inputs
  aws-region:
    description:
      "The region for pushing docker image. For public images ecr-login requires
      it to be us-east-1"
    required: false
    default: "us-east-1"
  aws-account-number:
    description: "Account number for pushing docker image"
    required: true
  aws-role-arn:
    description: "AWS role ARN for pushing docker image"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-duration-seconds: 900
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      with:
        registry-type: >-
          ${{
            startsWith(inputs.docker-manifest-name, 'public.ecr.aws/') &&
          'public'
              || 'private'
          }}
        registries: ${{ inputs.aws-account-number }}

    - name: Create and push Docker manifest
      id: create-push-docker-manifest
      shell: bash
      env:
        DOCKER_TAG:
          ${{ format('{0}:{1}', inputs.docker-manifest-name,
          inputs.docker-manifest-tag) }}
        DOCKER_IMAGE_NAME_DIGESTS: ${{ inputs.docker-image-name-digests }}
      run: |
        # Replaces commas with spaces.
        docker_image_names_with_digests=$(echo "${DOCKER_IMAGE_NAME_DIGESTS}" | tr ',' ' ')
        docker buildx imagetools create --tag "${DOCKER_TAG}" "${docker_image_names_with_digests}"
        echo "docker-tag=${DOCKER_TAG}" | tee -a "${GITHUB_OUTPUT}"

    - name: Install cosign
      if: inputs.docker-manifest-sign == 'true'
      uses: sigstore/cosign-installer@c56c2d3e59e4281cc41dea2217323ba5694b171e # v3.8.0
      with:
        cosign-release: "v2.4.2"

    - name: Sign Docker Manifest using GH OIDC
      if: inputs.docker-manifest-sign == 'true'
      shell: sh
      env:
        DOCKER_TAG: ${{ steps.create-push-docker-manifest.outputs.docker-tag }}
      run: cosign sign "${DOCKER_TAG}" --yes

    - name: Verify Docker image signature
      if:
        inputs.docker-manifest-sign == 'true' && inputs.cosign-oidc-identity !=
        ''
      shell: sh
      env:
        DOCKER_TAG: ${{ steps.create-push-docker-manifest.outputs.docker-tag }}
        OIDC_ISSUER: ${{ inputs.cosign-oidc-issuer }}
        OIDC_IDENTITY: ${{ inputs.cosign-oidc-identity }}
      run: |
        cosign verify "${DOCKER_TAG}" \
          --certificate-oidc-issuer "${OIDC_ISSUER}" \
          --certificate-identity "${OIDC_IDENTITY}"
