name: guard-from-missing-changesets
description: Fail if changeset files are missing

inputs:
  checkout:
    description: |
      Checkout the repo (full clone).

      If this is not set to true, the calling workflow must have a checkout
      step with `fetch-depth: 0`.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout full repo
      if: inputs.checkout == 'true'
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Install changesets
      shell: bash
      run: ${{ github.action_path }}/scripts/install-changesets.sh
    - name: Fail if changesets are missing
      shell: bash
      env:
        TRUNK_BRANCH: ${{ inputs.trunk-branch }}
      run: ${{ github.action_path }}/scripts/fail-if-changesets-missing.sh
