name: guard-from-missing-changesets
description: Fail if changeset files are missing

inputs:
  checkout:
    description: |
      Checkout the repo (full clone).

      If this is not set to true, the calling workflow must have a checkout
      step with `fetch-depth: 0`.
    required: false
    default: "false"
  # grafana cloud inputs
  gc-basic-auth:
    description: "grafana cloud basic auth"
    required: false
  gc-host:
    description: "grafana cloud hostname"
    required: false
  metrics-job-name:
    description: "grafana metrics job name"
    required: false
    default: guard-from-missing-changesets
  trunk-branch:
    description: "Trunk branch name"
    required: false
    default: main

runs:
  using: composite
  steps:
    - name: Checkout full repo
      if: inputs.checkout == 'true'
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Install changesets
      shell: bash
      run: ${{ github.action_path }}/scripts/install-changesets.sh
    - name: Fail if changesets are missing
      shell: bash
      env:
        TRUNK_BRANCH: ${{ inputs.trunk-branch }}
      run: ${{ github.action_path }}/scripts/fail-if-changesets-missing.sh
    - name: Collect metrics
      if: always()
      id: collect-gha-metrics
      uses: smartcontractkit/push-gha-metrics-action@d1618b772a97fd87e6505de97b872ee0b1f1729a
      with:
        basic-auth: ${{ inputs.gc-basic-auth }}
        hostname: ${{ inputs.gc-host }}
        this-job-name: ${{ inputs.metrics-job-name }}
      continue-on-error: true
