name: update-actions
description: "update-actions"

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  # aws inputs
  aws-role-duration-seconds:
    description: ""
    required: false
    default: "900"
  aws-region:
    description: ""
    required: true
  aws-role-arn:
    description: ""
    required: true
  aws-lambda-url:
    description: ""
    required: true
  aws-role-arn-updater:
    description: ""
    required: true
  aws-lambda-url-updater:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Setup gh token
      id: get-gh-token
      uses: smartcontractkit/.github/actions/setup-github-token@setup-github-token/v1
      with:
        aws-role-arn: ${{ inputs.aws-role-arn }}
        aws-lambda-url: ${{ inputs.aws-lambda-url }}
        aws-region: ${{ inputs.aws-region }}
        aws-role-duration-seconds: ${{ inputs.aws-role-duration-seconds }}

    - name: Setup gh token
      id: get-gh-token-updater
      uses: smartcontractkit/.github/actions/setup-github-token@setup-github-token/v1
      with:
        aws-role-arn: ${{ inputs.aws-role-arn-updater }}
        aws-lambda-url: ${{ inputs.aws-lambda-url-updater }}
        aws-region: ${{ inputs.aws-region }}
        aws-role-duration-seconds: ${{ inputs.aws-role-duration-seconds }}

    - name: Update custom action versions
      uses: smartcontractkit/.github/apps/update-action-versions@update-action-versions/0.3.0
      with:
        github-token: ${{ steps.get-gh-token-updater.outputs.access-token }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        token: ${{ steps.get-gh-token.outputs.access-token }}
        title: "chore(deps): bump github actions"
        commit-message: "chore(deps): bump github actions"
        branch: cl-action-updater
        author:
          "App Token Issuer Releng Renovate Bot
          <376532+app-token-issuer-releng-renovate[bot]@users.noreply.github.com>"
