name: update-actions
description: "update-actions"

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  # aws inputs
  aws-role-duration-seconds:
    description: ""
    required: false
    default: "900"
  aws-region:
    description: ""
    required: true
  aws-role-arn:
    description: ""
    required: true
  aws-lambda-url:
    description: ""
    required: true
  aws-role-arn-updater:
    description: ""
    required: true
  aws-lambda-url-updater:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Assume role capable of getting token from gati
      uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-duration-seconds: ${{ inputs.aws-role-duration-seconds }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true

    - name: Get github token from gati
      id: get-gh-token
      uses: smartcontractkit/chainlink-github-actions/github-app-token-issuer@main
      with:
        url: ${{ inputs.aws-lambda-url }}

    - name: Assume role capable of getting token from gati for updater
      uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
      with:
        role-to-assume: ${{ inputs.aws-role-arn-updater }}
        role-duration-seconds: ${{ inputs.aws-role-duration-seconds }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true

    - name: Get github token from gati for updater
      id: get-gh-token-updater
      uses: smartcontractkit/chainlink-github-actions/github-app-token-issuer@main
      with:
        url: ${{ inputs.aws-lambda-url-updater }}

    - name: Update custom action versions
      uses: smartcontractkit/.github/apps/update-action-versions@main
      with:
        github-token: ${{ steps.get-gh-token-updater.outputs.access-token }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
      with:
        token: ${{ steps.get-gh-token.outputs.access-token }}
        title: "chore(deps): bump github actions"
        commit-message: "chore(deps): bump github actions"
        branch: cl-action-updater
        author:
          "App Token Issuer Releng Renovate Bot
          <376532+app-token-issuer-releng-renovate[bot]@users.noreply.github.com>"
