name: ci-lint
description: Lint typescript code

inputs:
  # general inputs
  checkout-repo:
    description: "enable git checkout repo"
    required: false
    default: "true"
  checkout-repo-fetch-depth:
    description: "number of commits to fetch"
    required: false
    default: "0"
  check-only-affected:
    description: ""
    required: false
    default: "false"
  base-ref:
    description: ""
    required: false
    default: main
  # nodejs inputs
  node-version-file:
    description: ""
    required: false
    default: ".tool-versions"
  pnpm-version:
    description: ""
    required: false
    default: "^8.0.0"

runs:
  using: composite
  steps:
    - name: Checkout repo
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: ${{ inputs.checkout-repo-fetch-depth }}

    - name: Setup nodejs
      uses: smartcontractkit/.github/actions/setup-nodejs@main
      with:
        node-version-file: ${{ inputs.node-version-file }}
        pnpm-version: ${{ inputs.pnpm-version }}
        use-cache: "true"
        run-install: "true"
      continue-on-error: true

    - name: Run lint
      if: inputs.check-only-affected != 'true'
      shell: bash
      run: pnpm run lint

    - name: Run lint affected
      if: inputs.check-only-affected == 'true'
      shell: bash
      run: pnpm run lint:affected --base=${{ inputs.base-ref }}

    - name: Store lint result artifacts
      if: always()
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: ts-lint-results
        path: ./eslint-report.json
