name: branch-out-upload
description: "Processes JUnit XML reports and uploads to trunk.io"

inputs:
  junit-file-path:
    description: "Path to the JUnit XML file to be processed"
    required: true
    default: "./junit.xml"

  junit-enhancer-version:
    description: "The version of the action"
    default: "latest"
    required: false

  # trunk inputs
  trunk-org-slug:
    description: "The organization slug for Trunk.io"
    required: true

  trunk-token:
    description: "The token for Trunk.io"
    required: true

  trunk-upload-only:
    description: |
      Whether to only upload to Trunk.io, and not let Trunk.io fail the job.
      Useful when onboarding a repository, and letting Trunk gather data.
    required: false
    default: "false"

  trunk-job-url:
    description: "The URL to the job run"
    required: false

  trunk-previous-step-outcome:
    description:
      "The outcome of the testing step. Used to determine failure status of this
      action."
    required: true

  trunk-variant:
    description: |
      The variant of the test. Used to differentiate between the same test suite
      run in different environments (e.g., OSes, browsers, DON topologies).
    required: false

runs:
  using: composite
  steps:
    - name: Install JUnit Enhancer
      shell: bash
      env:
        VERSION: ${{ inputs.junit-enhancer-version }}
      run: |
        echo "::group::Install JUnit Enhancer"
        go install github.com/smartcontractkit/quarantine/cmd/junit-enhancer@${VERSION}
        echo "::endgroup::"

    - name: Run JUnit Enhancer
      id: run-junit-enhancer
      shell: bash
      env:
        JUNIT_PATH: ${{ inputs.junit-file-path }}
      run: |
        junit-enhancer -input ${JUNIT_PATH} -output ./junit-enhanced.xml -verbose

    - name: Upload Test Results to Trunk.io
      id: upload-to-trunk
      uses: trunk-io/analytics-uploader@f2631c653f9675d391e6e68cc877370db927c64c # v2.0.0
      continue-on-error: ${{ inputs.trunk-upload-only == 'true' }}
      env:
        TRUNK_TELEMETRY: "off"
        JOB_URL: ${{ inputs.job-url }}
      with:
        junit-paths: "./junit-enhanced.xml"
        org-slug: ${{ inputs.trunk-org-slug }}
        token: ${{ inputs.trunk-token }}
        previous-step-outcome: ${{ inputs.trunk-previous-step-outcome }}
        variant: ${{ inputs.trunk-variant }}

    - name: Explain Failures (if any)
      if: ${{ failure() }}
      shell: bash
      env:
        JUNIT_ENHANCER_OUTCOME: ${{ inputs.run-junit-enhancer.outcome }}
        TRUNK_UPLOAD_OUTCOME: ${{ inputs.upload-to-trunk.outcome }}
      run: |
        if [[ "${JUNIT_ENHANCER_OUTCOME}" == "failure" ]]; then
          echo "The JUnit Enhancer step failed. This is typically due to build failures while running unit tests. Please check the above logs for details."
        elif [[ "${TRUNK_UPLOAD_OUTCOME}" == "failure" ]]; then
          echo "The trunk upload step failed. This step determines whether to fail the workflow based on the contents of the junit test report, and the currently quarantined tests."
          echo "A failure here likely means that there were unquarantined unit test failures."
        else
          echo "The action failed for an unknown reason."
        fi
