name: branch-out-upload
description: "Processes JUnit XML reports and uploads to trunk.io"

inputs:
  test-suite-language:
    description: "The programming language of the test suite"
    required: true
    default: "go"

  junit-file-path:
    description: "Path to the JUnit XML file to be processed"
    required: true
    default: "./junit.xml"

  junit-enhancer-version:
    description: "The version of the action"
    default: "latest"
    required: false

  go-test-args:
    description:
      "Arguments to pass to the go test command. When set, this action runs the
      tests."
    required: false
    default: ""

  # trunk inputs
  trunk-org-slug:
    description: "The organization slug for Trunk.io"
    required: true

  trunk-token:
    description: "The token for Trunk.io"
    required: true

  trunk-upload-only:
    description: |
      Whether to only upload to Trunk.io, and not let Trunk.io fail the job.
      Useful when onboarding a repository, and letting Trunk gather data.
    required: false
    default: "false"

  trunk-job-url:
    description: "The URL to the job run"
    required: true
    default:
      ${{ format('https://github.com/{0}/actions/runs/{1}/job/{2}',
      github.repository, github.run_id, job.check_run_id) }}

  trunk-previous-step-outcome:
    description:
      "The outcome of the testing step. Used to determine failure status of this
      action. Required when go-test-args is not set."
    required: false
    default: ""

  trunk-variant:
    description: |
      The variant of the test. Used to differentiate between the same test suite
      run in different environments (e.g., OSes, browsers, DON topologies).
    required: false

runs:
  using: composite
  steps:
    - name: Process inputs
      id: inputs-ext
      shell: bash
      env:
        TEST_SUITE_LANGUAGE: ${{ inputs.test-suite-language }}
        JUNIT_FILE_PATH: ${{ inputs.junit-file-path }}
        GO_TEST_ARGS: ${{ inputs.go-test-args }}
        TRUNK_PREVIOUS_STEP_OUTCOME: ${{ inputs.trunk-previous-step-outcome }}
      run: |
        echo "Test suite language: $TEST_SUITE_LANGUAGE"
        JUNIT_DIR=$(dirname $JUNIT_FILE_PATH)
        echo "junit-dir=${JUNIT_DIR}" | tee -a "$GITHUB_OUTPUT"
        echo "JUnit directory: $JUNIT_DIR"
        echo "JUnit file path: $JUNIT_FILE_PATH"

        RUN_TESTS=false
        if [[ -n "$GO_TEST_ARGS" ]]; then
          RUN_TESTS=true
          echo "go-test-args provided; will run tests in this action."
        else
          echo "go-test-args not provided; will only upload results."
        fi
        echo "run-tests=${RUN_TESTS}" | tee -a "$GITHUB_OUTPUT"

        if [[ "${RUN_TESTS}" == "true" && "$TEST_SUITE_LANGUAGE" != "go" ]]; then
          echo "::error::go-test-args is only supported for Go test suites."
          exit 1
        fi

        if [[ "${RUN_TESTS}" == "false" && -z "${TRUNK_PREVIOUS_STEP_OUTCOME}" ]]; then
          echo "::error::trunk-previous-step-outcome is required when go-test-args is not set."
          exit 1
        fi

        if [[ "$TEST_SUITE_LANGUAGE" == "go" ]]; then
          echo "Go test suite detected, will run JUnit Enhancer."
          echo "run-enhancer=true" | tee -a "$GITHUB_OUTPUT"
          echo "junit-path-to-upload=./junit-enhanced.xml" | tee -a "$GITHUB_OUTPUT"
        else
          echo "Non-Go test suite detected, skipping JUnit Enhancer."
          echo "run-enhancer=false" | tee -a "$GITHUB_OUTPUT"
          echo "junit-path-to-upload=$JUNIT_FILE_PATH" | tee -a "$GITHUB_OUTPUT"
        fi

    - name: Install gotestsum
      if: ${{ steps.inputs-ext.outputs.run-tests == 'true' }}
      shell: bash
      run: |
        echo "::group::Install gotestsum"
        go install gotest.tools/gotestsum@latest
        echo "::endgroup::"

    - name: Run Go tests
      id: run-go-tests
      if: ${{ steps.inputs-ext.outputs.run-tests == 'true' }}
      continue-on-error: true
      shell: bash
      env:
        GO_TEST_ARGS: ${{ inputs.go-test-args }}
        JUNIT_FILE_PATH: ${{ inputs.junit-file-path }}
      run: |
        set -o pipefail
        read -r -a GO_TEST_ARGS_ARRAY <<< "${GO_TEST_ARGS}"
        COMMAND=(  
          gotestsum  
          --format standard-quiet  
          --hide-summary skipped  
          --junitfile "$JUNIT_FILE_PATH"  
          --  
          "${GO_TEST_ARGS_ARRAY[@]}"  
        )  
        echo "Running command: ${COMMAND[*]}"  
        "${COMMAND[@]}"

    - name: Install JUnit Enhancer (go)
      if: ${{ steps.inputs-ext.outputs.run-enhancer == 'true' }}
      shell: bash
      env:
        JUNIT_ENHANCER_VERSION: ${{ inputs.junit-enhancer-version }}
      run: |
        echo "::group::Install JUnit Enhancer"
        go install github.com/smartcontractkit/quarantine/cmd/junit-enhancer@${JUNIT_ENHANCER_VERSION}
        echo "::endgroup::"

    - name: Run JUnit Enhancer (go)
      id: run-junit-enhancer
      if: ${{ steps.inputs-ext.outputs.run-enhancer == 'true' }}
      # continue even if this step fails as it should still have produced an output file that we can upload.
      continue-on-error: true
      shell: bash
      env:
        JUNIT_INPUT_PATH: ${{ inputs.junit-file-path }}
        JUNIT_OUTPUT_PATH: ${{ steps.inputs-ext.outputs.junit-path-to-upload }}
      run: |
        junit-enhancer -input ${JUNIT_INPUT_PATH} -output ${JUNIT_OUTPUT_PATH} -verbose

    - name: Resolve previous step outcome
      id: resolve-previous-step-outcome
      if: ${{ always() }}
      shell: bash
      env:
        RUN_TESTS: ${{ steps.inputs-ext.outputs.run-tests }}
        TEST_OUTCOME: ${{ steps.run-go-tests.outcome }}
        TRUNK_PREVIOUS_STEP_OUTCOME: ${{ inputs.trunk-previous-step-outcome }}
      run: |
        if [[ "${RUN_TESTS}" == "true" ]]; then
          echo "previous-step-outcome=${TEST_OUTCOME}" | tee -a "$GITHUB_OUTPUT"
        else
          echo "previous-step-outcome=${TRUNK_PREVIOUS_STEP_OUTCOME}" | tee -a "$GITHUB_OUTPUT"
        fi

    - name: Upload Test Results to Trunk.io
      id: upload-to-trunk
      uses: trunk-io/analytics-uploader@293e9b144a101ef4b8fe3485a5afd0224fc48255 # v2.0.7
      continue-on-error: ${{ inputs.trunk-upload-only == 'true' }}
      env:
        TRUNK_TELEMETRY: "off"
        JOB_URL: ${{ inputs.job-url }}
      with:
        junit-paths: ${{ steps.inputs-ext.outputs.junit-path-to-upload }}
        org-slug: ${{ inputs.trunk-org-slug }}
        token: ${{ inputs.trunk-token }}
        previous-step-outcome:
          ${{ steps.resolve-previous-step-outcome.outputs.previous-step-outcome
          }}
        variant: ${{ inputs.trunk-variant }}

    - name: Check junit-enhancer outcomes
      shell: bash
      if: ${{ always() && steps.inputs-ext.outputs.run-enhancer == 'true' }}
      env:
        TRUNK_UPLOAD_ONLY: ${{ inputs.trunk-upload-only }}
        STEP_RESULT: ${{ steps.run-junit-enhancer.outcome }}
      run: |
        echo "Found junit-enhancer step result: ${STEP_RESULT}, and TRUNK_UPLOAD_ONLY is set to: ${TRUNK_UPLOAD_ONLY}"

        if [[ "${STEP_RESULT}" == "failure" ]]; then
          echo "::error::The JUnit Enhancer step failed. This is typically due to it detecting build failures or timeouts in the test reports."

          if [[ "${TRUNK_UPLOAD_ONLY}" == "false" ]]; then
            echo "::error::Failing the workflow as auto-quarantine is enabled, and junit-enhancer reported failures."
            exit 1
          fi
        fi

    - name: Upload test logs as artifact
      if: ${{ failure() && steps.inputs-ext.outputs.run-enhancer == 'true' }}
      uses: actions/upload-artifact@v5.0.0
      with:
        name: individual_test_logs
        path: "${{ steps.inputs-ext.outputs.junit-dir }}/raw-test-logs/"
        retention-days: 10
