name: branch-out-upload
description: "Processes JUnit XML reports and uploads to trunk.io"

inputs:
  junit-file-path:
    description: "Path to the JUnit XML file to be processed"
    required: true
    default: "./junit.xml"

  junit-enhancer-version:
    description: "The version of the action"
    default: "latest"
    required: false

  # trunk inputs
  trunk-org-slug:
    description: "The organization slug for Trunk.io"
    required: true

  trunk-token:
    description: "The token for Trunk.io"
    required: true

  trunk-upload-only:
    description: |
      Whether to only upload to Trunk.io, and not let Trunk.io fail the job.
      Useful when onboarding a repository, and letting Trunk gather data.
    required: false
    default: "false"

  trunk-job-url:
    description: "The URL to the job run"
    required: false

  trunk-previous-step-outcome:
    description: "The outcome of the previous step"
    required: true

runs:
  using: composite
  steps:
    - name: Install JUnit Enhancer and Run
      shell: bash
      env:
        VERSION: ${{ inputs.junit-enhancer-version }}
        JUNIT_PATH: ${{ inputs.junit-file-path }}
      run: |
        echo "::group::Install JUnit Enhancer"
        go install github.com/smartcontractkit/quarantine/cmd/junit-enhancer@${VERSION}
        echo "::endgroup::"

        echo "::group::Run JUnit Enhancer"
        junit-enhancer -input ${JUNIT_PATH} -output ./junit-enhanced.xml -verbose
        echo "::endgroup::"

    - name: Upload Test Results to Trunk.io
      uses: trunk-io/analytics-uploader@f2631c653f9675d391e6e68cc877370db927c64c # v2.0.0
      continue-on-error: ${{ inputs.trunk-upload-only == 'true' }}
      env:
        TRUNK_TELEMETRY: "off"
        JOB_URL: ${{ inputs.job-url }}
      with:
        junit-paths: "./junit-enhanced.xml"
        org-slug: ${{ inputs.trunk-org-slug }}
        token: ${{ inputs.trunk-token }}
        previous-step-outcome: ${{ inputs.trunk-previous-step-outcome }}
