name: branch-out-upload
description: "Processes JUnit XML reports and uploads to trunk.io"

inputs:
  junit-file-path:
    description: "Path to the JUnit XML file to be processed"
    required: true
    default: "./junit.xml"

  junit-enhancer-version:
    description: "The version of the action"
    default: "latest"
    required: false

  # trunk inputs
  trunk-org-slug:
    description: "The organization slug for Trunk.io"
    required: true

  trunk-token:
    description: "The token for Trunk.io"
    required: true

  trunk-upload-only:
    description: |
      Whether to only upload to Trunk.io, and not let Trunk.io fail the job.
      Useful when onboarding a repository, and letting Trunk gather data.
    required: false
    default: "false"

  trunk-job-url:
    description: "The URL to the job run"
    required: false

  trunk-previous-step-outcome:
    description:
      "The outcome of the testing step. Used to determine failure status of this
      action."
    required: true

  trunk-variant:
    description: |
      The variant of the test. Used to differentiate between the same test suite
      run in different environments (e.g., OSes, browsers, DON topologies).
    required: false

runs:
  using: composite
  steps:
    - name: Install JUnit Enhancer
      shell: bash
      env:
        VERSION: ${{ inputs.junit-enhancer-version }}
      run: |
        echo "::group::Install JUnit Enhancer"
        go install github.com/smartcontractkit/quarantine/cmd/junit-enhancer@${VERSION}
        echo "::endgroup::"

    - name: Run JUnit Enhancer
      id: run-junit-enhancer
      # continue even if this step fails as it should still have produced an output file that we can upload.
      continue-on-error: true
      shell: bash
      env:
        JUNIT_PATH: ${{ inputs.junit-file-path }}
      run: |
        junit-enhancer -input ${JUNIT_PATH} -output ./junit-enhanced.xml -verbose

    - name: Upload Test Results to Trunk.io
      id: upload-to-trunk
      uses: trunk-io/analytics-uploader@f2631c653f9675d391e6e68cc877370db927c64c # v2.0.0
      continue-on-error: ${{ inputs.trunk-upload-only == 'true' }}
      env:
        TRUNK_TELEMETRY: "off"
        JOB_URL: ${{ inputs.job-url }}
      with:
        junit-paths: "./junit-enhanced.xml"
        org-slug: ${{ inputs.trunk-org-slug }}
        token: ${{ inputs.trunk-token }}
        previous-step-outcome: ${{ inputs.trunk-previous-step-outcome }}
        variant: ${{ inputs.trunk-variant }}

    - name: Check junit-enhancer outcomes
      shell: bash
      if: ${{ always() }}
      env:
        TRUNK_UPLOAD_ONLY: ${{ inputs.trunk-upload-only }}
        STEP_RESULT: ${{ steps.run-junit-enhancer.outcome }}
      run: |
        echo "Found junit-enhancer step result: ${STEP_RESULT}, and TRUNK_UPLOAD_ONLY is set to: ${TRUNK_UPLOAD_ONLY}"

        if [[ "${STEP_RESULT}" == "failure" ]]; then
          echo "::error::The JUnit Enhancer step failed. This is typically due to it detecting build failures or timeouts in the test reports."

          if [[ "${TRUNK_UPLOAD_ONLY}" == "false" ]]; then
            echo "::error::Failing the workflow as auto-quarantine is enabled, and junit-enhancer reported failures."
            exit 1
          fi
        fi
