name: schedule-renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: Checkout repo (needed to reference local action)
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup github token
        id: get-access-token
        uses: smartcontractkit/.github/actions/setup-github-token@test/update-gati-action
        with:
          aws-role-arn: ${{ secrets.AWS_OIDC_IAM_ROLE_ARN_GATI }}
          aws-lambda-url: ${{ secrets.AWS_LAMBDA_URL_GATI }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-duration-seconds: 900

      - name: test token
        shell: bash
        run: aws sts get-caller-identity
