name: schedule-renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: Checkout repo (needed to reference local action)
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: setup-renovate
        uses: ./actions/setup-renovate
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn-gati: ${{ secrets.AWS_OIDC_IAM_ROLE_ARN_GATI }}
          aws-lambda-url-gati: ${{ secrets.AWS_LAMBDA_URL_GATI }}
