name: gha-workflow-validator
description: "Will validate workflow changes in a repository"

runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  validate-diff-only:
    description: "Only run validations against the diff."
    required: false
    default: true
  root-directory:
    description: "Root directory of the repository."
    required: false
    default: ${{ github.workspace }}
  validate-runners:
    description: "Validate the runners in the workflow are approved for use."
    required: false
    default: true
  validate-action-refs:
    description: "Validate action references use a SHA reference."
    required: false
    default: true
  validate-action-node-versions:
    description: "Validate action references are using node 20."
    required: false
    default: true
  include-all-action-definitions:
    description:
      "Include all action.yml files in the repository, not just the ones in
      .github/actions. Useful for action monorepos."
    required: false
    default: false
