name: gha-workflow-validator
description: "Will validate workflow changes in a repository"

runs:
  using: "node20"
  main: "dist/index.cjs"

inputs:
  placeholder:
    description: "placeholder"
    required: false